// Code generated by gen_bson.go. DO NOT EDIT.
package main

import (
	"fmt"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/x/bsonx/bsoncore"
	"strconv"
)

func (z *FieldSkip) MarshalBSON() ([]byte, error) {
	idx, dst := bsoncore.AppendDocumentStart(nil)
	dst = bsoncore.AppendStringElement(dst, "exported", z.Exported)
	if len(z.OmitMe) > 0 {
		dst = bsoncore.AppendStringElement(dst, "-", z.OmitMe)
	}
	dst, _ = bsoncore.AppendDocumentEnd(dst, idx)
	return dst, nil
}

func (z *FieldSkip) UnmarshalBSON(b []byte) error {
	_, data, ok := bsoncore.ReadLength(b)
	if !ok {
		return fmt.Errorf("invalid BSON document")
	}
	for len(data) > 0 && data[0] != 0 {
		elem, rem, ok := bsoncore.ReadElement(data)
		if !ok {
			return fmt.Errorf("invalid BSON element")
		}
		data = rem

		val := elem.Value()

		keyBytes := elem.KeyBytes()
		switch string(keyBytes) {
		case "exported":
			z.Exported = val.StringValue()
		case "-":
			z.OmitMe = val.StringValue()
		}
	}
	return nil
}

func (z *InlineBase) MarshalBSON() ([]byte, error) {
	idx, dst := bsoncore.AppendDocumentStart(nil)
	dst = bsoncore.AppendStringElement(dst, "bf1", z.BaseField1)
	dst = bsoncore.AppendInt32Element(dst, "bf2", int32(z.BaseField2))
	dst, _ = bsoncore.AppendDocumentEnd(dst, idx)
	return dst, nil
}

func (z *InlineBase) UnmarshalBSON(b []byte) error {
	_, data, ok := bsoncore.ReadLength(b)
	if !ok {
		return fmt.Errorf("invalid BSON document")
	}
	for len(data) > 0 && data[0] != 0 {
		elem, rem, ok := bsoncore.ReadElement(data)
		if !ok {
			return fmt.Errorf("invalid BSON element")
		}
		data = rem

		val := elem.Value()

		keyBytes := elem.KeyBytes()
		switch string(keyBytes) {
		case "bf1":
			z.BaseField1 = val.StringValue()
		case "bf2":
			z.BaseField2 = int(val.AsInt64())
		}
	}
	return nil
}

func (z *InlineStruct) MarshalBSON() ([]byte, error) {
	idx, dst := bsoncore.AppendDocumentStart(nil)
	dst = bsoncore.AppendStringElement(dst, "own", z.OwnField)
	dst = bsoncore.AppendStringElement(dst, "bf1", z.Inline.BaseField1)
	dst = bsoncore.AppendInt32Element(dst, "bf2", int32(z.Inline.BaseField2))
	dst, _ = bsoncore.AppendDocumentEnd(dst, idx)
	return dst, nil
}

func (z *InlineStruct) UnmarshalBSON(b []byte) error {
	_, data, ok := bsoncore.ReadLength(b)
	if !ok {
		return fmt.Errorf("invalid BSON document")
	}
	for len(data) > 0 && data[0] != 0 {
		elem, rem, ok := bsoncore.ReadElement(data)
		if !ok {
			return fmt.Errorf("invalid BSON element")
		}
		data = rem

		val := elem.Value()

		keyBytes := elem.KeyBytes()
		switch string(keyBytes) {
		case "own":
			z.OwnField = val.StringValue()
		case "bf1":
			z.Inline.BaseField1 = val.StringValue()
		case "bf2":
			z.Inline.BaseField2 = int(val.AsInt64())
		}
	}
	return nil
}

func (z *EmbedRef) MarshalBSON() ([]byte, error) {
	idx, dst := bsoncore.AppendDocumentStart(nil)
	dst = bsoncore.AppendStringElement(dst, "name", z.Name)
	dst, _ = bsoncore.AppendDocumentEnd(dst, idx)
	return dst, nil
}

func (z *EmbedRef) UnmarshalBSON(b []byte) error {
	_, data, ok := bsoncore.ReadLength(b)
	if !ok {
		return fmt.Errorf("invalid BSON document")
	}
	for len(data) > 0 && data[0] != 0 {
		elem, rem, ok := bsoncore.ReadElement(data)
		if !ok {
			return fmt.Errorf("invalid BSON element")
		}
		data = rem

		val := elem.Value()

		keyBytes := elem.KeyBytes()
		switch string(keyBytes) {
		case "name":
			z.Name = val.StringValue()
		}
	}
	return nil
}

func (z *EmbedOwner) MarshalBSON() ([]byte, error) {
	idx, dst := bsoncore.AppendDocumentStart(nil)
	dst = bsoncore.AppendStringElement(dst, "name", z.EmbedRef.Name)
	dst = bsoncore.AppendStringElement(dst, "extra", z.Extra)
	dst, _ = bsoncore.AppendDocumentEnd(dst, idx)
	return dst, nil
}

func (z *EmbedOwner) UnmarshalBSON(b []byte) error {
	_, data, ok := bsoncore.ReadLength(b)
	if !ok {
		return fmt.Errorf("invalid BSON document")
	}
	for len(data) > 0 && data[0] != 0 {
		elem, rem, ok := bsoncore.ReadElement(data)
		if !ok {
			return fmt.Errorf("invalid BSON element")
		}
		data = rem

		val := elem.Value()

		keyBytes := elem.KeyBytes()
		switch string(keyBytes) {
		case "name":
			z.EmbedRef.Name = val.StringValue()
		case "extra":
			z.Extra = val.StringValue()
		}
	}
	return nil
}

func (z *NestedSlices) MarshalBSON() ([]byte, error) {
	idx, dst := bsoncore.AppendDocumentStart(nil)
	if z.Matrix == nil {
		dst = bsoncore.AppendNullElement(dst, "matrix")
	} else {
		aIdx, aDst := bsoncore.AppendArrayStart(nil)
		for i, v := range z.Matrix {
			key := strconv.Itoa(i)
			{
				innerIdx, innerDst := bsoncore.AppendArrayStart(nil)
				for i, v := range v {
					k := strconv.Itoa(i)
					innerDst = bsoncore.AppendInt32Element(innerDst, k, v)
				}
				innerDst, _ = bsoncore.AppendArrayEnd(innerDst, innerIdx)
				aDst = bsoncore.AppendArrayElement(aDst, key, innerDst)
			}
		}
		aDst, _ = bsoncore.AppendArrayEnd(aDst, aIdx)
		dst = bsoncore.AppendArrayElement(dst, "matrix", aDst)
	}
	if z.Jagged == nil {
		dst = bsoncore.AppendNullElement(dst, "jagged")
	} else {
		aIdx, aDst := bsoncore.AppendArrayStart(nil)
		for i, v := range z.Jagged {
			key := strconv.Itoa(i)
			{
				innerIdx, innerDst := bsoncore.AppendArrayStart(nil)
				for i, v := range v {
					k := strconv.Itoa(i)
					innerDst = bsoncore.AppendStringElement(innerDst, k, v)
				}
				innerDst, _ = bsoncore.AppendArrayEnd(innerDst, innerIdx)
				aDst = bsoncore.AppendArrayElement(aDst, key, innerDst)
			}
		}
		aDst, _ = bsoncore.AppendArrayEnd(aDst, aIdx)
		dst = bsoncore.AppendArrayElement(dst, "jagged", aDst)
	}
	dst, _ = bsoncore.AppendDocumentEnd(dst, idx)
	return dst, nil
}

func (z *NestedSlices) UnmarshalBSON(b []byte) error {
	_, data, ok := bsoncore.ReadLength(b)
	if !ok {
		return fmt.Errorf("invalid BSON document")
	}
	for len(data) > 0 && data[0] != 0 {
		elem, rem, ok := bsoncore.ReadElement(data)
		if !ok {
			return fmt.Errorf("invalid BSON element")
		}
		data = rem

		val := elem.Value()

		keyBytes := elem.KeyBytes()
		switch string(keyBytes) {
		case "matrix":
			{
				if val.Type == 0x0A {
					z.Matrix = nil
					break
				}
				arrBytes, ok := val.ArrayOK()
				if !ok {
					return fmt.Errorf("字段 %s 不是数组类型", "matrix")
				}
				arrElems, err := bsoncore.Document(arrBytes).Elements()
				if err != nil {
					return err
				}
				z.Matrix = make([][]int32, 0, len(arrElems))
				for _, ae := range arrElems {
					{
						subArrBytes1, subArrOK2 := ae.Value().ArrayOK()
						if !subArrOK2 {
							return fmt.Errorf("数组元素不是数组类型")
						}
						subArrElems3, subArrErr4 := bsoncore.Document(subArrBytes1).Elements()
						if subArrErr4 != nil {
							return subArrErr4
						}
						subItem5 := make([]int32, 0, len(subArrElems3))
						for _, sae := range subArrElems3 {
							subItem5 = append(subItem5, sae.Value().Int32())
						}
						z.Matrix = append(z.Matrix, subItem5)
					}
				}
			}
		case "jagged":
			{
				if val.Type == 0x0A {
					z.Jagged = nil
					break
				}
				arrBytes, ok := val.ArrayOK()
				if !ok {
					return fmt.Errorf("字段 %s 不是数组类型", "jagged")
				}
				arrElems, err := bsoncore.Document(arrBytes).Elements()
				if err != nil {
					return err
				}
				z.Jagged = make([][]string, 0, len(arrElems))
				for _, ae := range arrElems {
					{
						subArrBytes6, subArrOK7 := ae.Value().ArrayOK()
						if !subArrOK7 {
							return fmt.Errorf("数组元素不是数组类型")
						}
						subArrElems8, subArrErr9 := bsoncore.Document(subArrBytes6).Elements()
						if subArrErr9 != nil {
							return subArrErr9
						}
						subItem10 := make([]string, 0, len(subArrElems8))
						for _, sae := range subArrElems8 {
							subItem10 = append(subItem10, sae.Value().StringValue())
						}
						z.Jagged = append(z.Jagged, subItem10)
					}
				}
			}
		}
	}
	return nil
}

func (z *PtrItem) MarshalBSON() ([]byte, error) {
	idx, dst := bsoncore.AppendDocumentStart(nil)
	dst = bsoncore.AppendStringElement(dst, "val", z.Val)
	dst, _ = bsoncore.AppendDocumentEnd(dst, idx)
	return dst, nil
}

func (z *PtrItem) UnmarshalBSON(b []byte) error {
	_, data, ok := bsoncore.ReadLength(b)
	if !ok {
		return fmt.Errorf("invalid BSON document")
	}
	for len(data) > 0 && data[0] != 0 {
		elem, rem, ok := bsoncore.ReadElement(data)
		if !ok {
			return fmt.Errorf("invalid BSON element")
		}
		data = rem

		val := elem.Value()

		keyBytes := elem.KeyBytes()
		switch string(keyBytes) {
		case "val":
			z.Val = val.StringValue()
		}
	}
	return nil
}

func (z *PtrSlice) MarshalBSON() ([]byte, error) {
	idx, dst := bsoncore.AppendDocumentStart(nil)
	if z.Items == nil {
		dst = bsoncore.AppendNullElement(dst, "items")
	} else {
		aIdx, aDst := bsoncore.AppendArrayStart(nil)
		for i, v := range z.Items {
			key := strconv.Itoa(i)
			if v != nil {
				{
					subBytes, err := (*v).MarshalBSON()
					if err != nil {
						return nil, err
					}
					aDst = bsoncore.AppendDocumentElement(aDst, key, subBytes)
				}
			} else {
				aDst = bsoncore.AppendNullElement(aDst, key)
			}
		}
		aDst, _ = bsoncore.AppendArrayEnd(aDst, aIdx)
		dst = bsoncore.AppendArrayElement(dst, "items", aDst)
	}
	dst, _ = bsoncore.AppendDocumentEnd(dst, idx)
	return dst, nil
}

func (z *PtrSlice) UnmarshalBSON(b []byte) error {
	_, data, ok := bsoncore.ReadLength(b)
	if !ok {
		return fmt.Errorf("invalid BSON document")
	}
	for len(data) > 0 && data[0] != 0 {
		elem, rem, ok := bsoncore.ReadElement(data)
		if !ok {
			return fmt.Errorf("invalid BSON element")
		}
		data = rem

		val := elem.Value()

		keyBytes := elem.KeyBytes()
		switch string(keyBytes) {
		case "items":
			{
				if val.Type == 0x0A {
					z.Items = nil
					break
				}
				arrBytes, ok := val.ArrayOK()
				if !ok {
					return fmt.Errorf("字段 %s 不是数组类型", "items")
				}
				arrElems, err := bsoncore.Document(arrBytes).Elements()
				if err != nil {
					return err
				}
				z.Items = make([]*PtrItem, 0, len(arrElems))
				for _, ae := range arrElems {
					{
						if ae.Value().Type == 0x0A {
							z.Items = append(z.Items, nil)
						} else {
							subBytes, ok := ae.Value().DocumentOK()
							if !ok {
								return fmt.Errorf("数组元素不是文档类型")
							}
							subItem := new(PtrItem)
							if err := subItem.UnmarshalBSON(subBytes); err != nil {
								return err
							}
							z.Items = append(z.Items, subItem)
						}
					}
				}
			}
		}
	}
	return nil
}

func (z *AnonymousStruct) MarshalBSON() ([]byte, error) {
	idx, dst := bsoncore.AppendDocumentStart(nil)
	{
		aj, ajDst := bsoncore.AppendDocumentStart(nil)
		ajDst = bsoncore.AppendInt32Element(ajDst, "ns", z.Onboarding.NextStep)
		if z.Onboarding.DoneList == nil {
			ajDst = bsoncore.AppendNullElement(ajDst, "dl")
		} else {
			aIdx, aDst := bsoncore.AppendArrayStart(nil)
			for i, v := range z.Onboarding.DoneList {
				key := strconv.Itoa(i)
				aDst = bsoncore.AppendInt32Element(aDst, key, v)
			}
			aDst, _ = bsoncore.AppendArrayEnd(aDst, aIdx)
			ajDst = bsoncore.AppendArrayElement(ajDst, "dl", aDst)
		}
		ajDst, _ = bsoncore.AppendDocumentEnd(ajDst, aj)
		dst = bsoncore.AppendDocumentElement(dst, "onboarding", ajDst)
	}
	{
		aj, ajDst := bsoncore.AppendDocumentStart(nil)
		ajDst = bsoncore.AppendInt64Element(ajDst, "f", z.IAP.AccFlags)
		ajDst = bsoncore.AppendStringElement(ajDst, "sku", z.IAP.SKU)
		ajDst, _ = bsoncore.AppendDocumentEnd(ajDst, aj)
		dst = bsoncore.AppendDocumentElement(dst, "iap", ajDst)
	}
	dst, _ = bsoncore.AppendDocumentEnd(dst, idx)
	return dst, nil
}

func (z *AnonymousStruct) UnmarshalBSON(b []byte) error {
	_, data, ok := bsoncore.ReadLength(b)
	if !ok {
		return fmt.Errorf("invalid BSON document")
	}
	for len(data) > 0 && data[0] != 0 {
		elem, rem, ok := bsoncore.ReadElement(data)
		if !ok {
			return fmt.Errorf("invalid BSON element")
		}
		data = rem

		val := elem.Value()

		keyBytes := elem.KeyBytes()
		switch string(keyBytes) {
		case "onboarding":
			{
				subBytes, ok := val.DocumentOK()
				if !ok {
					return fmt.Errorf("field is not document")
				}
				subElems, err := bsoncore.Document(subBytes).Elements()
				if err != nil {
					return err
				}
				for _, se := range subElems {
					switch se.Key() {
					case "ns":
						z.Onboarding.NextStep = se.Value().Int32()
					case "dl":
						{
							if se.Value().Type == 0x0A {
								z.Onboarding.DoneList = nil
								break
							}
							arrBytes, ok := se.Value().ArrayOK()
							if !ok {
								return fmt.Errorf("field is not array")
							}
							arrElems, err := bsoncore.Document(arrBytes).Elements()
							if err != nil {
								return err
							}
							z.Onboarding.DoneList = make([]int32, 0, len(arrElems))
							for _, ae := range arrElems {
								z.Onboarding.DoneList = append(z.Onboarding.DoneList, ae.Value().Int32())
							}
						}
					}
				}
			}
		case "iap":
			{
				subBytes, ok := val.DocumentOK()
				if !ok {
					return fmt.Errorf("field is not document")
				}
				subElems, err := bsoncore.Document(subBytes).Elements()
				if err != nil {
					return err
				}
				for _, se := range subElems {
					switch se.Key() {
					case "f":
						z.IAP.AccFlags = se.Value().AsInt64()
					case "sku":
						z.IAP.SKU = se.Value().StringValue()
					}
				}
			}
		}
	}
	return nil
}

func (z *IntWidths) MarshalBSON() ([]byte, error) {
	idx, dst := bsoncore.AppendDocumentStart(nil)
	dst = bsoncore.AppendInt32Element(dst, "i8", int32(z.I8))
	dst = bsoncore.AppendInt32Element(dst, "i16", int32(z.I16))
	dst = bsoncore.AppendInt32Element(dst, "i32", z.I32)
	dst = bsoncore.AppendInt64Element(dst, "i64", z.I64)
	dst = bsoncore.AppendInt32Element(dst, "ui8", int32(z.UI8))
	dst = bsoncore.AppendInt32Element(dst, "ui16", int32(z.UI16))
	dst = bsoncore.AppendInt64Element(dst, "ui32", int64(z.UI32))
	if z.UI64 > 9223372036854775807 {
		return nil, fmt.Errorf("字段 %s 超出 int64 范围", "ui64")
	}
	dst = bsoncore.AppendInt64Element(dst, "ui64", int64(z.UI64))
	dst = bsoncore.AppendInt32Element(dst, "int", int32(z.Int))
	if uint64(z.Uint) > 9223372036854775807 {
		return nil, fmt.Errorf("字段 %s 超出 int64 范围", "uint")
	}
	dst = bsoncore.AppendInt64Element(dst, "uint", int64(z.Uint))
	dst, _ = bsoncore.AppendDocumentEnd(dst, idx)
	return dst, nil
}

func (z *IntWidths) UnmarshalBSON(b []byte) error {
	_, data, ok := bsoncore.ReadLength(b)
	if !ok {
		return fmt.Errorf("invalid BSON document")
	}
	for len(data) > 0 && data[0] != 0 {
		elem, rem, ok := bsoncore.ReadElement(data)
		if !ok {
			return fmt.Errorf("invalid BSON element")
		}
		data = rem

		val := elem.Value()

		keyBytes := elem.KeyBytes()
		switch string(keyBytes) {
		case "i8":
			z.I8 = int8(val.AsInt64())
		case "i16":
			z.I16 = int16(val.AsInt64())
		case "i32":
			z.I32 = val.Int32()
		case "i64":
			z.I64 = val.AsInt64()
		case "ui8":
			z.UI8 = byte(val.AsInt64())
		case "ui16":
			z.UI16 = uint16(val.AsInt64())
		case "ui32":
			z.UI32 = uint32(val.AsInt64())
		case "ui64":
			z.UI64 = uint64(val.AsInt64())
		case "int":
			z.Int = int(val.AsInt64())
		case "uint":
			z.Uint = uint(val.AsInt64())
		}
	}
	return nil
}

func (z *ZeroValues) MarshalBSON() ([]byte, error) {
	idx, dst := bsoncore.AppendDocumentStart(nil)
	dst = bsoncore.AppendStringElement(dst, "str", z.Str)
	dst = bsoncore.AppendBooleanElement(dst, "bool", z.Bool)
	dst = bsoncore.AppendInt32Element(dst, "i32", z.I32)
	dst = bsoncore.AppendDoubleElement(dst, "f64", z.F64)
	if z.Bytes == nil {
		dst = bsoncore.AppendNullElement(dst, "bytes")
	} else {
		dst = bsoncore.AppendBinaryElement(dst, "bytes", 0, z.Bytes)
	}
	if z.Slice == nil {
		dst = bsoncore.AppendNullElement(dst, "slice")
	} else {
		aIdx, aDst := bsoncore.AppendArrayStart(nil)
		for i, v := range z.Slice {
			key := strconv.Itoa(i)
			aDst = bsoncore.AppendStringElement(aDst, key, v)
		}
		aDst, _ = bsoncore.AppendArrayEnd(aDst, aIdx)
		dst = bsoncore.AppendArrayElement(dst, "slice", aDst)
	}
	if z.Map == nil {
		dst = bsoncore.AppendNullElement(dst, "map")
	} else {
		mIdx, mDst := bsoncore.AppendDocumentStart(nil)
		for k, v := range z.Map {
			mDst = bsoncore.AppendInt32Element(mDst, k, int32(v))
		}
		mDst, _ = bsoncore.AppendDocumentEnd(mDst, mIdx)
		dst = bsoncore.AppendDocumentElement(dst, "map", mDst)
	}
	if z.Ptr != nil {
		dst = bsoncore.AppendStringElement(dst, "ptr", *z.Ptr)
	} else {
		dst = bsoncore.AppendNullElement(dst, "ptr")
	}
	dst = bsoncore.AppendDateTimeElement(dst, "time", z.Time.UnixMilli())
	if len(z.OptStr) > 0 {
		dst = bsoncore.AppendStringElement(dst, "opt_str", z.OptStr)
	}
	if z.OptI32 != 0 {
		dst = bsoncore.AppendInt32Element(dst, "opt_i32", z.OptI32)
	}
	if z.OptBool {
		dst = bsoncore.AppendBooleanElement(dst, "opt_bool", z.OptBool)
	}
	if z.OptPtr != nil {
		dst = bsoncore.AppendStringElement(dst, "opt_ptr", *z.OptPtr)
	}
	dst, _ = bsoncore.AppendDocumentEnd(dst, idx)
	return dst, nil
}

func (z *ZeroValues) UnmarshalBSON(b []byte) error {
	_, data, ok := bsoncore.ReadLength(b)
	if !ok {
		return fmt.Errorf("invalid BSON document")
	}
	for len(data) > 0 && data[0] != 0 {
		elem, rem, ok := bsoncore.ReadElement(data)
		if !ok {
			return fmt.Errorf("invalid BSON element")
		}
		data = rem

		val := elem.Value()

		keyBytes := elem.KeyBytes()
		switch string(keyBytes) {
		case "str":
			z.Str = val.StringValue()
		case "bool":
			z.Bool = val.Boolean()
		case "i32":
			z.I32 = val.Int32()
		case "f64":
			z.F64 = val.Double()
		case "bytes":
			if val.Type == 0x0A {
				z.Bytes = nil
			} else {
				_, z.Bytes, _ = val.BinaryOK()
			}
		case "slice":
			{
				if val.Type == 0x0A {
					z.Slice = nil
					break
				}
				arrBytes, ok := val.ArrayOK()
				if !ok {
					return fmt.Errorf("字段 %s 不是数组类型", "slice")
				}
				arrElems, err := bsoncore.Document(arrBytes).Elements()
				if err != nil {
					return err
				}
				z.Slice = make([]string, 0, len(arrElems))
				for _, ae := range arrElems {
					z.Slice = append(z.Slice, ae.Value().StringValue())
				}
			}
		case "map":
			{
				if val.Type == 0x0A {
					z.Map = nil
					break
				}
				mapBytes, ok := val.DocumentOK()
				if !ok {
					return fmt.Errorf("字段 %s 不是文档类型", "map")
				}
				mapElems, err := bsoncore.Document(mapBytes).Elements()
				if err != nil {
					return err
				}
				z.Map = make(map[string]int, len(mapElems))
				for _, me := range mapElems {
					z.Map[me.Key()] = int(me.Value().AsInt64())
				}
			}
		case "ptr":
			{
				if val.Type == 0x0A {
					z.Ptr = nil
					break
				}
				tmp := val.StringValue()
				z.Ptr = &tmp
			}
		case "time":
			z.Time = primitive.DateTime(val.DateTime()).Time()
		case "opt_str":
			z.OptStr = val.StringValue()
		case "opt_i32":
			z.OptI32 = val.Int32()
		case "opt_bool":
			z.OptBool = val.Boolean()
		case "opt_ptr":
			{
				if val.Type == 0x0A {
					z.OptPtr = nil
					break
				}
				tmp := val.StringValue()
				z.OptPtr = &tmp
			}
		}
	}
	return nil
}

func (z *BattleStats) MarshalBSON() ([]byte, error) {
	idx, dst := bsoncore.AppendDocumentStart(nil)
	dst = bsoncore.AppendInt32Element(dst, "wins", z.Wins)
	dst = bsoncore.AppendInt32Element(dst, "losses", z.Losses)
	dst = bsoncore.AppendInt32Element(dst, "rating", z.Rating)
	dst, _ = bsoncore.AppendDocumentEnd(dst, idx)
	return dst, nil
}

func (z *BattleStats) UnmarshalBSON(b []byte) error {
	_, data, ok := bsoncore.ReadLength(b)
	if !ok {
		return fmt.Errorf("invalid BSON document")
	}
	for len(data) > 0 && data[0] != 0 {
		elem, rem, ok := bsoncore.ReadElement(data)
		if !ok {
			return fmt.Errorf("invalid BSON element")
		}
		data = rem

		val := elem.Value()

		keyBytes := elem.KeyBytes()
		switch string(keyBytes) {
		case "wins":
			z.Wins = val.Int32()
		case "losses":
			z.Losses = val.Int32()
		case "rating":
			z.Rating = val.Int32()
		}
	}
	return nil
}

func (z *Bag) MarshalBSON() ([]byte, error) {
	idx, dst := bsoncore.AppendDocumentStart(nil)
	dst = bsoncore.AppendInt64Element(dst, "gold", z.Gold)
	if z.Items == nil {
		dst = bsoncore.AppendNullElement(dst, "items")
	} else {
		aIdx, aDst := bsoncore.AppendArrayStart(nil)
		for i, v := range z.Items {
			key := strconv.Itoa(i)
			aDst = bsoncore.AppendInt32Element(aDst, key, v)
		}
		aDst, _ = bsoncore.AppendArrayEnd(aDst, aIdx)
		dst = bsoncore.AppendArrayElement(dst, "items", aDst)
	}
	dst, _ = bsoncore.AppendDocumentEnd(dst, idx)
	return dst, nil
}

func (z *Bag) UnmarshalBSON(b []byte) error {
	_, data, ok := bsoncore.ReadLength(b)
	if !ok {
		return fmt.Errorf("invalid BSON document")
	}
	for len(data) > 0 && data[0] != 0 {
		elem, rem, ok := bsoncore.ReadElement(data)
		if !ok {
			return fmt.Errorf("invalid BSON element")
		}
		data = rem

		val := elem.Value()

		keyBytes := elem.KeyBytes()
		switch string(keyBytes) {
		case "gold":
			z.Gold = val.AsInt64()
		case "items":
			{
				if val.Type == 0x0A {
					z.Items = nil
					break
				}
				arrBytes, ok := val.ArrayOK()
				if !ok {
					return fmt.Errorf("字段 %s 不是数组类型", "items")
				}
				arrElems, err := bsoncore.Document(arrBytes).Elements()
				if err != nil {
					return err
				}
				z.Items = make([]int32, 0, len(arrElems))
				for _, ae := range arrElems {
					z.Items = append(z.Items, ae.Value().Int32())
				}
			}
		}
	}
	return nil
}

func (z *Player) MarshalBSON() ([]byte, error) {
	idx, dst := bsoncore.AppendDocumentStart(nil)
	dst = bsoncore.AppendInt64Element(dst, "_id", z.ID)
	dst = bsoncore.AppendInt64Element(dst, "account_id", z.AccountID)
	dst = bsoncore.AppendStringElement(dst, "name", z.Name)
	dst = bsoncore.AppendInt32Element(dst, "lv", z.Level)
	dst = bsoncore.AppendInt32Element(dst, "exp", z.Exp)
	dst = bsoncore.AppendInt32Element(dst, "head", z.Head)
	dst = bsoncore.AppendInt32Element(dst, "vip", z.VipLevel)
	dst = bsoncore.AppendInt32Element(dst, "tag", z.Tag)
	dst = bsoncore.AppendInt32Element(dst, "rate", int32(z.Rate))
	dst = bsoncore.AppendBooleanElement(dst, "load", z.Load)
	dst = bsoncore.AppendBooleanElement(dst, "renamed", z.HasRenamed)
	if z.OfflineFight != nil {
		{
			aj, ajDst := bsoncore.AppendDocumentStart(nil)
			ajDst = bsoncore.AppendInt32Element(ajDst, "id", z.OfflineFight.ID)
			ajDst = bsoncore.AppendStringElement(ajDst, "name", z.OfflineFight.Name)
			ajDst = bsoncore.AppendInt32Element(ajDst, "hp", z.OfflineFight.HP)
			ajDst = bsoncore.AppendInt32Element(ajDst, "mp", z.OfflineFight.MP)
			ajDst, _ = bsoncore.AppendDocumentEnd(ajDst, aj)
			dst = bsoncore.AppendDocumentElement(dst, "offline_fight", ajDst)
		}
	}
	if len(z.Heros) > 0 {
		aIdx, aDst := bsoncore.AppendArrayStart(nil)
		for i, v := range z.Heros {
			key := strconv.Itoa(i)
			if v != nil {
				{
					subIdx, subDst := bsoncore.AppendDocumentStart(nil)
					subDst = bsoncore.AppendInt32Element(subDst, "id", (*v).ID)
					subDst = bsoncore.AppendStringElement(subDst, "name", (*v).Name)
					subDst = bsoncore.AppendInt32Element(subDst, "hp", (*v).HP)
					subDst = bsoncore.AppendInt32Element(subDst, "mp", (*v).MP)
					subDst, _ = bsoncore.AppendDocumentEnd(subDst, subIdx)
					aDst = bsoncore.AppendDocumentElement(aDst, key, subDst)
				}
			} else {
				aDst = bsoncore.AppendNullElement(aDst, key)
			}
		}
		aDst, _ = bsoncore.AppendArrayEnd(aDst, aIdx)
		dst = bsoncore.AppendArrayElement(dst, "heros", aDst)
	}
	{
		subBytes, err := z.Bag.MarshalBSON()
		if err != nil {
			return nil, err
		}
		dst = bsoncore.AppendDocumentElement(dst, "bag", subBytes)
	}
	if len(z.SalePackages) > 0 {
		aIdx, aDst := bsoncore.AppendArrayStart(nil)
		for i, v := range z.SalePackages {
			key := strconv.Itoa(i)
			if v != nil {
				{
					subBytes, err := bson.Marshal((*v))
					if err != nil {
						return nil, err
					}
					aDst = bsoncore.AppendDocumentElement(aDst, key, subBytes)
				}
			} else {
				aDst = bsoncore.AppendNullElement(aDst, key)
			}
		}
		aDst, _ = bsoncore.AppendArrayEnd(aDst, aIdx)
		dst = bsoncore.AppendArrayElement(dst, "sale_pkgs", aDst)
	}
	if len(z.ClientFilter) > 0 {
		aIdx, aDst := bsoncore.AppendArrayStart(nil)
		for i, v := range z.ClientFilter {
			key := strconv.Itoa(i)
			{
				innerIdx, innerDst := bsoncore.AppendArrayStart(nil)
				for i, v := range v {
					k := strconv.Itoa(i)
					innerDst = bsoncore.AppendInt32Element(innerDst, k, v)
				}
				innerDst, _ = bsoncore.AppendArrayEnd(innerDst, innerIdx)
				aDst = bsoncore.AppendArrayElement(aDst, key, innerDst)
			}
		}
		aDst, _ = bsoncore.AppendArrayEnd(aDst, aIdx)
		dst = bsoncore.AppendArrayElement(dst, "cdf", aDst)
	}
	if len(z.PBCounters) > 0 {
		aIdx, aDst := bsoncore.AppendArrayStart(nil)
		for i, v := range z.PBCounters {
			key := strconv.Itoa(i)
			{
				subBytes, err := bson.Marshal(v)
				if err != nil {
					return nil, err
				}
				aDst = bsoncore.AppendDocumentElement(aDst, key, subBytes)
			}
		}
		aDst, _ = bsoncore.AppendArrayEnd(aDst, aIdx)
		dst = bsoncore.AppendArrayElement(dst, "pbcs", aDst)
	}
	if z.BossDropSeqs == nil {
		dst = bsoncore.AppendNullElement(dst, "bds")
	} else {
		aIdx, aDst := bsoncore.AppendArrayStart(nil)
		for i, v := range z.BossDropSeqs {
			key := strconv.Itoa(i)
			{
				subBytes, err := bson.Marshal(v)
				if err != nil {
					return nil, err
				}
				aDst = bsoncore.AppendDocumentElement(aDst, key, subBytes)
			}
		}
		aDst, _ = bsoncore.AppendArrayEnd(aDst, aIdx)
		dst = bsoncore.AppendArrayElement(dst, "bds", aDst)
	}
	if z.Bids == nil {
		dst = bsoncore.AppendNullElement(dst, "bids")
	} else {
		aIdx, aDst := bsoncore.AppendArrayStart(nil)
		for i, v := range z.Bids {
			key := strconv.Itoa(i)
			aDst = bsoncore.AppendStringElement(aDst, key, v)
		}
		aDst, _ = bsoncore.AppendArrayEnd(aDst, aIdx)
		dst = bsoncore.AppendArrayElement(dst, "bids", aDst)
	}
	if len(z.SubChan) > 0 {
		aIdx, aDst := bsoncore.AppendArrayStart(nil)
		for i, v := range z.SubChan {
			key := strconv.Itoa(i)
			aDst = bsoncore.AppendStringElement(aDst, key, v)
		}
		aDst, _ = bsoncore.AppendArrayEnd(aDst, aIdx)
		dst = bsoncore.AppendArrayElement(dst, "sub_chan", aDst)
	}
	if len(z.ActiveContracts) > 0 {
		aIdx, aDst := bsoncore.AppendArrayStart(nil)
		for i, v := range z.ActiveContracts {
			key := strconv.Itoa(i)
			aDst = bsoncore.AppendInt32Element(aDst, key, v)
		}
		aDst, _ = bsoncore.AppendArrayEnd(aDst, aIdx)
		dst = bsoncore.AppendArrayElement(dst, "contracts", aDst)
	}
	dst = bsoncore.AppendInt32Element(dst, "nid", int32(z.AutoIncrementID))
	{
		subBytes, err := z.Statue.MarshalBSON()
		if err != nil {
			return nil, err
		}
		dst = bsoncore.AppendDocumentElement(dst, "statues", subBytes)
	}
	dst, _ = bsoncore.AppendDocumentEnd(dst, idx)
	return dst, nil
}

func (z *Player) UnmarshalBSON(b []byte) error {
	_, data, ok := bsoncore.ReadLength(b)
	if !ok {
		return fmt.Errorf("invalid BSON document")
	}
	for len(data) > 0 && data[0] != 0 {
		elem, rem, ok := bsoncore.ReadElement(data)
		if !ok {
			return fmt.Errorf("invalid BSON element")
		}
		data = rem

		val := elem.Value()

		keyBytes := elem.KeyBytes()
		switch string(keyBytes) {
		case "_id":
			z.ID = val.AsInt64()
		case "account_id":
			z.AccountID = val.AsInt64()
		case "name":
			z.Name = val.StringValue()
		case "lv":
			z.Level = val.Int32()
		case "exp":
			z.Exp = val.Int32()
		case "head":
			z.Head = val.Int32()
		case "vip":
			z.VipLevel = val.Int32()
		case "tag":
			z.Tag = val.Int32()
		case "rate":
			z.Rate = int8(val.AsInt64())
		case "load":
			z.Load = val.Boolean()
		case "renamed":
			z.HasRenamed = val.Boolean()
		case "offline_fight":
			{
				if val.Type == 0x0A {
					z.OfflineFight = nil
					break
				}
				val, ok := val.DocumentOK()
				if ok {
					z.OfflineFight = new(Hero)
					subBytes11, subOK12 := bsoncore.Value{Type: 0x03, Data: val}.DocumentOK()
					if !subOK12 {
						return fmt.Errorf("字段 %s 不是文档类型", "offline_fight")
					}
					subElems13, subErr14 := bsoncore.Document(subBytes11).Elements()
					if subErr14 != nil {
						return subErr14
					}
					for _, subElem15 := range subElems13 {
						switch subElem15.Key() {
						case "id":
							z.OfflineFight.ID = subElem15.Value().Int32()
						case "name":
							z.OfflineFight.Name = subElem15.Value().StringValue()
						case "hp":
							z.OfflineFight.HP = subElem15.Value().Int32()
						case "mp":
							z.OfflineFight.MP = subElem15.Value().Int32()
						}
					}
				} else {
					z.OfflineFight = nil
				}
			}
		case "heros":
			{
				if val.Type == 0x0A {
					z.Heros = nil
					break
				}
				arrBytes, ok := val.ArrayOK()
				if !ok {
					return fmt.Errorf("字段 %s 不是数组类型", "heros")
				}
				arrElems, err := bsoncore.Document(arrBytes).Elements()
				if err != nil {
					return err
				}
				z.Heros = make([]*Hero, 0, len(arrElems))
				for _, ae := range arrElems {
					{
						if ae.Value().Type == 0x0A {
							z.Heros = append(z.Heros, nil)
						} else {
							subBytes, ok := ae.Value().DocumentOK()
							if !ok {
								return fmt.Errorf("数组元素不是文档类型")
							}
							subItem := new(Hero)
							subBytes16, subOK17 := bsoncore.Value{Type: 0x03, Data: subBytes}.DocumentOK()
							if !subOK17 {
								return fmt.Errorf("字段 %s 不是文档类型", "数组元素")
							}
							subElems18, subErr19 := bsoncore.Document(subBytes16).Elements()
							if subErr19 != nil {
								return subErr19
							}
							for _, subElem20 := range subElems18 {
								switch subElem20.Key() {
								case "id":
									subItem.ID = subElem20.Value().Int32()
								case "name":
									subItem.Name = subElem20.Value().StringValue()
								case "hp":
									subItem.HP = subElem20.Value().Int32()
								case "mp":
									subItem.MP = subElem20.Value().Int32()
								}
							}
							z.Heros = append(z.Heros, subItem)
						}
					}
				}
			}
		case "bag":
			{
				subBytes, ok := val.DocumentOK()
				if !ok {
					return fmt.Errorf("字段 %s 不是文档类型", "bag")
				}
				if err := z.Bag.UnmarshalBSON(subBytes); err != nil {
					return err
				}
			}
		case "sale_pkgs":
			{
				if val.Type == 0x0A {
					z.SalePackages = nil
					break
				}
				arrBytes, ok := val.ArrayOK()
				if !ok {
					return fmt.Errorf("字段 %s 不是数组类型", "sale_pkgs")
				}
				arrElems, err := bsoncore.Document(arrBytes).Elements()
				if err != nil {
					return err
				}
				z.SalePackages = make([]*struct {
					ID   int32  `bson:"id"`
					Name string `bson:"name"`
				}, 0, len(arrElems))
				for _, ae := range arrElems {
					{
						subBytes, ok := ae.Value().DocumentOK()
						if !ok {
							return fmt.Errorf("数组元素不是文档类型")
						}
						var subItem *struct {
							ID   int32  `bson:"id"`
							Name string `bson:"name"`
						}
						if err := bson.Unmarshal(subBytes, &subItem); err != nil {
							return err
						}
						z.SalePackages = append(z.SalePackages, subItem)
					}
				}
			}
		case "cdf":
			{
				if val.Type == 0x0A {
					z.ClientFilter = nil
					break
				}
				arrBytes, ok := val.ArrayOK()
				if !ok {
					return fmt.Errorf("字段 %s 不是数组类型", "cdf")
				}
				arrElems, err := bsoncore.Document(arrBytes).Elements()
				if err != nil {
					return err
				}
				z.ClientFilter = make([][]int32, 0, len(arrElems))
				for _, ae := range arrElems {
					{
						subArrBytes21, subArrOK22 := ae.Value().ArrayOK()
						if !subArrOK22 {
							return fmt.Errorf("数组元素不是数组类型")
						}
						subArrElems23, subArrErr24 := bsoncore.Document(subArrBytes21).Elements()
						if subArrErr24 != nil {
							return subArrErr24
						}
						subItem25 := make([]int32, 0, len(subArrElems23))
						for _, sae := range subArrElems23 {
							subItem25 = append(subItem25, sae.Value().Int32())
						}
						z.ClientFilter = append(z.ClientFilter, subItem25)
					}
				}
			}
		case "pbcs":
			{
				if val.Type == 0x0A {
					z.PBCounters = nil
					break
				}
				arrBytes, ok := val.ArrayOK()
				if !ok {
					return fmt.Errorf("字段 %s 不是数组类型", "pbcs")
				}
				arrElems, err := bsoncore.Document(arrBytes).Elements()
				if err != nil {
					return err
				}
				z.PBCounters = make([]map[string]int64, 0, len(arrElems))
				for _, ae := range arrElems {
					{
						subMapBytes26, subMapOK27 := ae.Value().DocumentOK()
						if !subMapOK27 {
							return fmt.Errorf("数组元素不是文档类型")
						}
						subMapElems28, subMapErr29 := bsoncore.Document(subMapBytes26).Elements()
						if subMapErr29 != nil {
							return subMapErr29
						}
						subItem30 := make(map[string]int64, len(subMapElems28))
						for _, sme := range subMapElems28 {
							subItem30[sme.Key()] = sme.Value().AsInt64()
						}
						z.PBCounters = append(z.PBCounters, subItem30)
					}
				}
			}
		case "bds":
			{
				if val.Type == 0x0A {
					z.BossDropSeqs = nil
					break
				}
				arrBytes, ok := val.ArrayOK()
				if !ok {
					return fmt.Errorf("字段 %s 不是数组类型", "bds")
				}
				arrElems, err := bsoncore.Document(arrBytes).Elements()
				if err != nil {
					return err
				}
				z.BossDropSeqs = make([]map[string]int64, 0, len(arrElems))
				for _, ae := range arrElems {
					{
						subMapBytes31, subMapOK32 := ae.Value().DocumentOK()
						if !subMapOK32 {
							return fmt.Errorf("数组元素不是文档类型")
						}
						subMapElems33, subMapErr34 := bsoncore.Document(subMapBytes31).Elements()
						if subMapErr34 != nil {
							return subMapErr34
						}
						subItem35 := make(map[string]int64, len(subMapElems33))
						for _, sme := range subMapElems33 {
							subItem35[sme.Key()] = sme.Value().AsInt64()
						}
						z.BossDropSeqs = append(z.BossDropSeqs, subItem35)
					}
				}
			}
		case "bids":
			{
				if val.Type == 0x0A {
					z.Bids = nil
					break
				}
				arrBytes, ok := val.ArrayOK()
				if !ok {
					return fmt.Errorf("字段 %s 不是数组类型", "bids")
				}
				arrElems, err := bsoncore.Document(arrBytes).Elements()
				if err != nil {
					return err
				}
				z.Bids = make([]string, 0, len(arrElems))
				for _, ae := range arrElems {
					z.Bids = append(z.Bids, ae.Value().StringValue())
				}
			}
		case "sub_chan":
			{
				if val.Type == 0x0A {
					z.SubChan = nil
					break
				}
				arrBytes, ok := val.ArrayOK()
				if !ok {
					return fmt.Errorf("字段 %s 不是数组类型", "sub_chan")
				}
				arrElems, err := bsoncore.Document(arrBytes).Elements()
				if err != nil {
					return err
				}
				z.SubChan = make([]string, 0, len(arrElems))
				for _, ae := range arrElems {
					z.SubChan = append(z.SubChan, ae.Value().StringValue())
				}
			}
		case "contracts":
			{
				if val.Type == 0x0A {
					z.ActiveContracts = nil
					break
				}
				arrBytes, ok := val.ArrayOK()
				if !ok {
					return fmt.Errorf("字段 %s 不是数组类型", "contracts")
				}
				arrElems, err := bsoncore.Document(arrBytes).Elements()
				if err != nil {
					return err
				}
				z.ActiveContracts = make([]int32, 0, len(arrElems))
				for _, ae := range arrElems {
					z.ActiveContracts = append(z.ActiveContracts, ae.Value().Int32())
				}
			}
		case "nid":
			z.AutoIncrementID = int(val.AsInt64())
		case "statues":
			{
				subBytes, ok := val.DocumentOK()
				if !ok {
					return fmt.Errorf("字段 %s 不是文档类型", "statues")
				}
				if err := z.Statue.UnmarshalBSON(subBytes); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

func (z *StatueInfo) MarshalBSON() ([]byte, error) {
	idx, dst := bsoncore.AppendDocumentStart(nil)
	dst = bsoncore.AppendInt32Element(dst, "c", z.Count)
	dst = bsoncore.AppendBooleanElement(dst, "active", z.Active)
	dst, _ = bsoncore.AppendDocumentEnd(dst, idx)
	return dst, nil
}

func (z *StatueInfo) UnmarshalBSON(b []byte) error {
	_, data, ok := bsoncore.ReadLength(b)
	if !ok {
		return fmt.Errorf("invalid BSON document")
	}
	for len(data) > 0 && data[0] != 0 {
		elem, rem, ok := bsoncore.ReadElement(data)
		if !ok {
			return fmt.Errorf("invalid BSON element")
		}
		data = rem

		val := elem.Value()

		keyBytes := elem.KeyBytes()
		switch string(keyBytes) {
		case "c":
			z.Count = val.Int32()
		case "active":
			z.Active = val.Boolean()
		}
	}
	return nil
}

func (z *WideStruct) MarshalBSON() ([]byte, error) {
	idx, dst := bsoncore.AppendDocumentStart(nil)
	dst = bsoncore.AppendInt32Element(dst, "a", z.A)
	dst = bsoncore.AppendInt32Element(dst, "b", z.B)
	dst = bsoncore.AppendInt32Element(dst, "c", z.C)
	dst = bsoncore.AppendInt32Element(dst, "d", z.D)
	dst = bsoncore.AppendInt32Element(dst, "e", z.E)
	dst = bsoncore.AppendInt32Element(dst, "f", z.F)
	dst = bsoncore.AppendInt32Element(dst, "g", z.G)
	dst = bsoncore.AppendInt32Element(dst, "h", z.H)
	dst = bsoncore.AppendInt32Element(dst, "i", z.I)
	dst = bsoncore.AppendInt32Element(dst, "j", z.J)
	dst = bsoncore.AppendInt32Element(dst, "k", z.K)
	dst = bsoncore.AppendInt32Element(dst, "l", z.L)
	dst = bsoncore.AppendInt32Element(dst, "m", z.M)
	dst = bsoncore.AppendInt32Element(dst, "n", z.N)
	dst = bsoncore.AppendInt32Element(dst, "o", z.O)
	dst = bsoncore.AppendInt32Element(dst, "p", z.P)
	dst = bsoncore.AppendInt32Element(dst, "q", z.Q)
	dst = bsoncore.AppendInt32Element(dst, "r", z.R)
	dst = bsoncore.AppendInt32Element(dst, "s", z.S)
	dst = bsoncore.AppendInt32Element(dst, "t", z.T)
	dst = bsoncore.AppendInt32Element(dst, "u", z.U)
	dst = bsoncore.AppendInt32Element(dst, "v", z.V)
	dst = bsoncore.AppendInt32Element(dst, "w", z.W)
	dst = bsoncore.AppendInt32Element(dst, "x", z.X)
	dst = bsoncore.AppendInt32Element(dst, "y", z.Y)
	dst = bsoncore.AppendInt32Element(dst, "z", z.Z)
	dst, _ = bsoncore.AppendDocumentEnd(dst, idx)
	return dst, nil
}

func (z *WideStruct) UnmarshalBSON(b []byte) error {
	_, data, ok := bsoncore.ReadLength(b)
	if !ok {
		return fmt.Errorf("invalid BSON document")
	}
	for len(data) > 0 && data[0] != 0 {
		elem, rem, ok := bsoncore.ReadElement(data)
		if !ok {
			return fmt.Errorf("invalid BSON element")
		}
		data = rem

		val := elem.Value()

		keyBytes := elem.KeyBytes()
		switch string(keyBytes) {
		case "a":
			z.A = val.Int32()
		case "b":
			z.B = val.Int32()
		case "c":
			z.C = val.Int32()
		case "d":
			z.D = val.Int32()
		case "e":
			z.E = val.Int32()
		case "f":
			z.F = val.Int32()
		case "g":
			z.G = val.Int32()
		case "h":
			z.H = val.Int32()
		case "i":
			z.I = val.Int32()
		case "j":
			z.J = val.Int32()
		case "k":
			z.K = val.Int32()
		case "l":
			z.L = val.Int32()
		case "m":
			z.M = val.Int32()
		case "n":
			z.N = val.Int32()
		case "o":
			z.O = val.Int32()
		case "p":
			z.P = val.Int32()
		case "q":
			z.Q = val.Int32()
		case "r":
			z.R = val.Int32()
		case "s":
			z.S = val.Int32()
		case "t":
			z.T = val.Int32()
		case "u":
			z.U = val.Int32()
		case "v":
			z.V = val.Int32()
		case "w":
			z.W = val.Int32()
		case "x":
			z.X = val.Int32()
		case "y":
			z.Y = val.Int32()
		case "z":
			z.Z = val.Int32()
		}
	}
	return nil
}
