// Code generated by gen_bson.go. DO NOT EDIT.
package main

import (
	"bytes"
	"fmt"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/x/bsonx/bsoncore"
	"strconv"
)

func (z *FieldSkip) MarshalBSON() ([]byte, error) {
	idx, dst := bsoncore.AppendDocumentStart(nil)
	dst = bsoncore.AppendStringElement(dst, "exported", z.Exported)
	if len(z.OmitMe) > 0 {
		dst = bsoncore.AppendStringElement(dst, "-", z.OmitMe)
	}
	dst, _ = bsoncore.AppendDocumentEnd(dst, idx)
	return dst, nil
}

func (z *FieldSkip) UnmarshalBSON(b []byte) error {
	_, data, ok := bsoncore.ReadLength(b)
	if !ok {
		return fmt.Errorf("invalid BSON document")
	}
	for len(data) > 0 && data[0] != 0 {
		elem, rem, ok := bsoncore.ReadElement(data)
		if !ok {
			return fmt.Errorf("invalid BSON element")
		}
		data = rem

		raw := []byte(elem)
		val := elem.Value()

		// Find key length
		keyLen := 0
		for raw[1+keyLen] != 0 {
			keyLen++
		}
		keyBytes := raw[1 : 1+keyLen]

		switch keyLen {
		case 1:
			switch uint64(keyBytes[0]) << 0 {
			case uint64('-') << 0:
				z.OmitMe = val.StringValue()
			default:
			}
		case 8:
			switch uint64(keyBytes[0])<<0 | uint64(keyBytes[1])<<8 | uint64(keyBytes[2])<<16 | uint64(keyBytes[3])<<24 | uint64(keyBytes[4])<<32 | uint64(keyBytes[5])<<40 | uint64(keyBytes[6])<<48 | uint64(keyBytes[7])<<56 {
			case uint64('e')<<0 | uint64('x')<<8 | uint64('p')<<16 | uint64('o')<<24 | uint64('r')<<32 | uint64('t')<<40 | uint64('e')<<48 | uint64('d')<<56:
				z.Exported = val.StringValue()
			default:
			}
		default:
			// unknown key length — skip
		}
	}
	return nil
}

func (z *InlineBase) MarshalBSON() ([]byte, error) {
	idx, dst := bsoncore.AppendDocumentStart(nil)
	dst = bsoncore.AppendStringElement(dst, "bf1", z.BaseField1)
	dst = bsoncore.AppendInt32Element(dst, "bf2", int32(z.BaseField2))
	dst, _ = bsoncore.AppendDocumentEnd(dst, idx)
	return dst, nil
}

func (z *InlineBase) UnmarshalBSON(b []byte) error {
	_, data, ok := bsoncore.ReadLength(b)
	if !ok {
		return fmt.Errorf("invalid BSON document")
	}
	for len(data) > 0 && data[0] != 0 {
		elem, rem, ok := bsoncore.ReadElement(data)
		if !ok {
			return fmt.Errorf("invalid BSON element")
		}
		data = rem

		raw := []byte(elem)
		val := elem.Value()

		// Find key length
		keyLen := 0
		for raw[1+keyLen] != 0 {
			keyLen++
		}
		keyBytes := raw[1 : 1+keyLen]

		switch keyLen {
		case 3:
			switch uint64(keyBytes[0])<<0 | uint64(keyBytes[1])<<8 | uint64(keyBytes[2])<<16 {
			case uint64('b')<<0 | uint64('f')<<8 | uint64('1')<<16:
				z.BaseField1 = val.StringValue()
			case uint64('b')<<0 | uint64('f')<<8 | uint64('2')<<16:
				z.BaseField2 = int(val.AsInt64())
			default:
			}
		default:
			// unknown key length — skip
		}
	}
	return nil
}

func (z *InlineStruct) MarshalBSON() ([]byte, error) {
	idx, dst := bsoncore.AppendDocumentStart(nil)
	dst = bsoncore.AppendStringElement(dst, "own", z.OwnField)
	dst = bsoncore.AppendStringElement(dst, "bf1", z.Inline.BaseField1)
	dst = bsoncore.AppendInt32Element(dst, "bf2", int32(z.Inline.BaseField2))
	dst, _ = bsoncore.AppendDocumentEnd(dst, idx)
	return dst, nil
}

func (z *InlineStruct) UnmarshalBSON(b []byte) error {
	_, data, ok := bsoncore.ReadLength(b)
	if !ok {
		return fmt.Errorf("invalid BSON document")
	}
	for len(data) > 0 && data[0] != 0 {
		elem, rem, ok := bsoncore.ReadElement(data)
		if !ok {
			return fmt.Errorf("invalid BSON element")
		}
		data = rem

		raw := []byte(elem)
		val := elem.Value()

		// Find key length
		keyLen := 0
		for raw[1+keyLen] != 0 {
			keyLen++
		}
		keyBytes := raw[1 : 1+keyLen]

		switch keyLen {
		case 3:
			switch uint64(keyBytes[0])<<0 | uint64(keyBytes[1])<<8 | uint64(keyBytes[2])<<16 {
			case uint64('o')<<0 | uint64('w')<<8 | uint64('n')<<16:
				z.OwnField = val.StringValue()
			case uint64('b')<<0 | uint64('f')<<8 | uint64('1')<<16:
				z.Inline.BaseField1 = val.StringValue()
			case uint64('b')<<0 | uint64('f')<<8 | uint64('2')<<16:
				z.Inline.BaseField2 = int(val.AsInt64())
			default:
			}
		default:
			// unknown key length — skip
		}
	}
	return nil
}

func (z *EmbedRef) MarshalBSON() ([]byte, error) {
	idx, dst := bsoncore.AppendDocumentStart(nil)
	dst = bsoncore.AppendStringElement(dst, "name", z.Name)
	dst, _ = bsoncore.AppendDocumentEnd(dst, idx)
	return dst, nil
}

func (z *EmbedRef) UnmarshalBSON(b []byte) error {
	_, data, ok := bsoncore.ReadLength(b)
	if !ok {
		return fmt.Errorf("invalid BSON document")
	}
	for len(data) > 0 && data[0] != 0 {
		elem, rem, ok := bsoncore.ReadElement(data)
		if !ok {
			return fmt.Errorf("invalid BSON element")
		}
		data = rem

		raw := []byte(elem)
		val := elem.Value()

		// Find key length
		keyLen := 0
		for raw[1+keyLen] != 0 {
			keyLen++
		}
		keyBytes := raw[1 : 1+keyLen]

		switch keyLen {
		case 4:
			switch uint64(keyBytes[0])<<0 | uint64(keyBytes[1])<<8 | uint64(keyBytes[2])<<16 | uint64(keyBytes[3])<<24 {
			case uint64('n')<<0 | uint64('a')<<8 | uint64('m')<<16 | uint64('e')<<24:
				z.Name = val.StringValue()
			default:
			}
		default:
			// unknown key length — skip
		}
	}
	return nil
}

func (z *EmbedOwner) MarshalBSON() ([]byte, error) {
	idx, dst := bsoncore.AppendDocumentStart(nil)
	dst = bsoncore.AppendStringElement(dst, "name", z.EmbedRef.Name)
	dst = bsoncore.AppendStringElement(dst, "extra", z.Extra)
	dst, _ = bsoncore.AppendDocumentEnd(dst, idx)
	return dst, nil
}

func (z *EmbedOwner) UnmarshalBSON(b []byte) error {
	_, data, ok := bsoncore.ReadLength(b)
	if !ok {
		return fmt.Errorf("invalid BSON document")
	}
	for len(data) > 0 && data[0] != 0 {
		elem, rem, ok := bsoncore.ReadElement(data)
		if !ok {
			return fmt.Errorf("invalid BSON element")
		}
		data = rem

		raw := []byte(elem)
		val := elem.Value()

		// Find key length
		keyLen := 0
		for raw[1+keyLen] != 0 {
			keyLen++
		}
		keyBytes := raw[1 : 1+keyLen]

		switch keyLen {
		case 4:
			switch uint64(keyBytes[0])<<0 | uint64(keyBytes[1])<<8 | uint64(keyBytes[2])<<16 | uint64(keyBytes[3])<<24 {
			case uint64('n')<<0 | uint64('a')<<8 | uint64('m')<<16 | uint64('e')<<24:
				z.EmbedRef.Name = val.StringValue()
			default:
			}
		case 5:
			switch uint64(keyBytes[0])<<0 | uint64(keyBytes[1])<<8 | uint64(keyBytes[2])<<16 | uint64(keyBytes[3])<<24 | uint64(keyBytes[4])<<32 {
			case uint64('e')<<0 | uint64('x')<<8 | uint64('t')<<16 | uint64('r')<<24 | uint64('a')<<32:
				z.Extra = val.StringValue()
			default:
			}
		default:
			// unknown key length — skip
		}
	}
	return nil
}

func (z *NestedSlices) MarshalBSON() ([]byte, error) {
	idx, dst := bsoncore.AppendDocumentStart(nil)
	if z.Matrix == nil {
		dst = bsoncore.AppendNullElement(dst, "matrix")
	} else {
		aIdx, aDst := bsoncore.AppendArrayStart(nil)
		for i, v := range z.Matrix {
			key := strconv.Itoa(i)
			{
				innerIdx, innerDst := bsoncore.AppendArrayStart(nil)
				for i, v := range v {
					k := strconv.Itoa(i)
					innerDst = bsoncore.AppendInt32Element(innerDst, k, v)
				}
				innerDst, _ = bsoncore.AppendArrayEnd(innerDst, innerIdx)
				aDst = bsoncore.AppendArrayElement(aDst, key, innerDst)
			}
		}
		aDst, _ = bsoncore.AppendArrayEnd(aDst, aIdx)
		dst = bsoncore.AppendArrayElement(dst, "matrix", aDst)
	}
	if z.Jagged == nil {
		dst = bsoncore.AppendNullElement(dst, "jagged")
	} else {
		aIdx, aDst := bsoncore.AppendArrayStart(nil)
		for i, v := range z.Jagged {
			key := strconv.Itoa(i)
			{
				innerIdx, innerDst := bsoncore.AppendArrayStart(nil)
				for i, v := range v {
					k := strconv.Itoa(i)
					innerDst = bsoncore.AppendStringElement(innerDst, k, v)
				}
				innerDst, _ = bsoncore.AppendArrayEnd(innerDst, innerIdx)
				aDst = bsoncore.AppendArrayElement(aDst, key, innerDst)
			}
		}
		aDst, _ = bsoncore.AppendArrayEnd(aDst, aIdx)
		dst = bsoncore.AppendArrayElement(dst, "jagged", aDst)
	}
	dst, _ = bsoncore.AppendDocumentEnd(dst, idx)
	return dst, nil
}

func (z *NestedSlices) UnmarshalBSON(b []byte) error {
	_, data, ok := bsoncore.ReadLength(b)
	if !ok {
		return fmt.Errorf("invalid BSON document")
	}
	for len(data) > 0 && data[0] != 0 {
		elem, rem, ok := bsoncore.ReadElement(data)
		if !ok {
			return fmt.Errorf("invalid BSON element")
		}
		data = rem

		raw := []byte(elem)
		val := elem.Value()

		// Find key length
		keyLen := 0
		for raw[1+keyLen] != 0 {
			keyLen++
		}
		keyBytes := raw[1 : 1+keyLen]

		switch keyLen {
		case 6:
			switch uint64(keyBytes[0])<<0 | uint64(keyBytes[1])<<8 | uint64(keyBytes[2])<<16 | uint64(keyBytes[3])<<24 | uint64(keyBytes[4])<<32 | uint64(keyBytes[5])<<40 {
			case uint64('m')<<0 | uint64('a')<<8 | uint64('t')<<16 | uint64('r')<<24 | uint64('i')<<32 | uint64('x')<<40:
				{
					if val.Type == 0x0A {
						z.Matrix = nil
						break
					}
					arrBytes, ok := val.ArrayOK()
					if !ok {
						return fmt.Errorf("字段 %s 不是数组类型", "matrix")
					}
					arrElems, err := bsoncore.Document(arrBytes).Elements()
					if err != nil {
						return err
					}
					z.Matrix = make([][]int32, 0, len(arrElems))
					for _, ae := range arrElems {
						{
							subArrBytes1, subArrOK2 := ae.Value().ArrayOK()
							if !subArrOK2 {
								return fmt.Errorf("数组元素不是数组类型")
							}
							subArrElems3, subArrErr4 := bsoncore.Document(subArrBytes1).Elements()
							if subArrErr4 != nil {
								return subArrErr4
							}
							subItem5 := make([]int32, 0, len(subArrElems3))
							for _, sae := range subArrElems3 {
								subItem5 = append(subItem5, sae.Value().Int32())
							}
							z.Matrix = append(z.Matrix, subItem5)
						}
					}
				}
			case uint64('j')<<0 | uint64('a')<<8 | uint64('g')<<16 | uint64('g')<<24 | uint64('e')<<32 | uint64('d')<<40:
				{
					if val.Type == 0x0A {
						z.Jagged = nil
						break
					}
					arrBytes, ok := val.ArrayOK()
					if !ok {
						return fmt.Errorf("字段 %s 不是数组类型", "jagged")
					}
					arrElems, err := bsoncore.Document(arrBytes).Elements()
					if err != nil {
						return err
					}
					z.Jagged = make([][]string, 0, len(arrElems))
					for _, ae := range arrElems {
						{
							subArrBytes6, subArrOK7 := ae.Value().ArrayOK()
							if !subArrOK7 {
								return fmt.Errorf("数组元素不是数组类型")
							}
							subArrElems8, subArrErr9 := bsoncore.Document(subArrBytes6).Elements()
							if subArrErr9 != nil {
								return subArrErr9
							}
							subItem10 := make([]string, 0, len(subArrElems8))
							for _, sae := range subArrElems8 {
								subItem10 = append(subItem10, sae.Value().StringValue())
							}
							z.Jagged = append(z.Jagged, subItem10)
						}
					}
				}
			default:
			}
		default:
			// unknown key length — skip
		}
	}
	return nil
}

func (z *PtrItem) MarshalBSON() ([]byte, error) {
	idx, dst := bsoncore.AppendDocumentStart(nil)
	dst = bsoncore.AppendStringElement(dst, "val", z.Val)
	dst, _ = bsoncore.AppendDocumentEnd(dst, idx)
	return dst, nil
}

func (z *PtrItem) UnmarshalBSON(b []byte) error {
	_, data, ok := bsoncore.ReadLength(b)
	if !ok {
		return fmt.Errorf("invalid BSON document")
	}
	for len(data) > 0 && data[0] != 0 {
		elem, rem, ok := bsoncore.ReadElement(data)
		if !ok {
			return fmt.Errorf("invalid BSON element")
		}
		data = rem

		raw := []byte(elem)
		val := elem.Value()

		// Find key length
		keyLen := 0
		for raw[1+keyLen] != 0 {
			keyLen++
		}
		keyBytes := raw[1 : 1+keyLen]

		switch keyLen {
		case 3:
			switch uint64(keyBytes[0])<<0 | uint64(keyBytes[1])<<8 | uint64(keyBytes[2])<<16 {
			case uint64('v')<<0 | uint64('a')<<8 | uint64('l')<<16:
				z.Val = val.StringValue()
			default:
			}
		default:
			// unknown key length — skip
		}
	}
	return nil
}

func (z *PtrSlice) MarshalBSON() ([]byte, error) {
	idx, dst := bsoncore.AppendDocumentStart(nil)
	if z.Items == nil {
		dst = bsoncore.AppendNullElement(dst, "items")
	} else {
		aIdx, aDst := bsoncore.AppendArrayStart(nil)
		for i, v := range z.Items {
			key := strconv.Itoa(i)
			if v != nil {
				{
					subBytes, err := (*v).MarshalBSON()
					if err != nil {
						return nil, err
					}
					aDst = bsoncore.AppendDocumentElement(aDst, key, subBytes)
				}
			} else {
				aDst = bsoncore.AppendNullElement(aDst, key)
			}
		}
		aDst, _ = bsoncore.AppendArrayEnd(aDst, aIdx)
		dst = bsoncore.AppendArrayElement(dst, "items", aDst)
	}
	dst, _ = bsoncore.AppendDocumentEnd(dst, idx)
	return dst, nil
}

func (z *PtrSlice) UnmarshalBSON(b []byte) error {
	_, data, ok := bsoncore.ReadLength(b)
	if !ok {
		return fmt.Errorf("invalid BSON document")
	}
	for len(data) > 0 && data[0] != 0 {
		elem, rem, ok := bsoncore.ReadElement(data)
		if !ok {
			return fmt.Errorf("invalid BSON element")
		}
		data = rem

		raw := []byte(elem)
		val := elem.Value()

		// Find key length
		keyLen := 0
		for raw[1+keyLen] != 0 {
			keyLen++
		}
		keyBytes := raw[1 : 1+keyLen]

		switch keyLen {
		case 5:
			switch uint64(keyBytes[0])<<0 | uint64(keyBytes[1])<<8 | uint64(keyBytes[2])<<16 | uint64(keyBytes[3])<<24 | uint64(keyBytes[4])<<32 {
			case uint64('i')<<0 | uint64('t')<<8 | uint64('e')<<16 | uint64('m')<<24 | uint64('s')<<32:
				{
					if val.Type == 0x0A {
						z.Items = nil
						break
					}
					arrBytes, ok := val.ArrayOK()
					if !ok {
						return fmt.Errorf("字段 %s 不是数组类型", "items")
					}
					arrElems, err := bsoncore.Document(arrBytes).Elements()
					if err != nil {
						return err
					}
					z.Items = make([]*PtrItem, 0, len(arrElems))
					for _, ae := range arrElems {
						{
							if ae.Value().Type == 0x0A {
								z.Items = append(z.Items, nil)
							} else {
								subBytes, ok := ae.Value().DocumentOK()
								if !ok {
									return fmt.Errorf("数组元素不是文档类型")
								}
								subItem := new(PtrItem)
								if err := subItem.UnmarshalBSON(subBytes); err != nil {
									return err
								}
								z.Items = append(z.Items, subItem)
							}
						}
					}
				}
			default:
			}
		default:
			// unknown key length — skip
		}
	}
	return nil
}

func (z *AnonymousStruct) MarshalBSON() ([]byte, error) {
	idx, dst := bsoncore.AppendDocumentStart(nil)
	{
		aj, ajDst := bsoncore.AppendDocumentStart(nil)
		ajDst = bsoncore.AppendInt32Element(ajDst, "ns", z.Onboarding.NextStep)
		if z.Onboarding.DoneList == nil {
			ajDst = bsoncore.AppendNullElement(ajDst, "dl")
		} else {
			aIdx, aDst := bsoncore.AppendArrayStart(nil)
			for i, v := range z.Onboarding.DoneList {
				key := strconv.Itoa(i)
				aDst = bsoncore.AppendInt32Element(aDst, key, v)
			}
			aDst, _ = bsoncore.AppendArrayEnd(aDst, aIdx)
			ajDst = bsoncore.AppendArrayElement(ajDst, "dl", aDst)
		}
		ajDst, _ = bsoncore.AppendDocumentEnd(ajDst, aj)
		dst = bsoncore.AppendDocumentElement(dst, "onboarding", ajDst)
	}
	{
		aj, ajDst := bsoncore.AppendDocumentStart(nil)
		ajDst = bsoncore.AppendInt64Element(ajDst, "f", z.IAP.AccFlags)
		ajDst = bsoncore.AppendStringElement(ajDst, "sku", z.IAP.SKU)
		ajDst, _ = bsoncore.AppendDocumentEnd(ajDst, aj)
		dst = bsoncore.AppendDocumentElement(dst, "iap", ajDst)
	}
	dst, _ = bsoncore.AppendDocumentEnd(dst, idx)
	return dst, nil
}

func (z *AnonymousStruct) UnmarshalBSON(b []byte) error {
	_, data, ok := bsoncore.ReadLength(b)
	if !ok {
		return fmt.Errorf("invalid BSON document")
	}
	for len(data) > 0 && data[0] != 0 {
		elem, rem, ok := bsoncore.ReadElement(data)
		if !ok {
			return fmt.Errorf("invalid BSON element")
		}
		data = rem

		raw := []byte(elem)
		val := elem.Value()

		// Find key length
		keyLen := 0
		for raw[1+keyLen] != 0 {
			keyLen++
		}
		keyBytes := raw[1 : 1+keyLen]

		switch keyLen {
		case 3:
			switch uint64(keyBytes[0])<<0 | uint64(keyBytes[1])<<8 | uint64(keyBytes[2])<<16 {
			case uint64('i')<<0 | uint64('a')<<8 | uint64('p')<<16:
				{
					subBytes, ok := val.DocumentOK()
					if !ok {
						return fmt.Errorf("field is not document")
					}
					subElems, err := bsoncore.Document(subBytes).Elements()
					if err != nil {
						return err
					}
					for _, se := range subElems {
						switch se.Key() {
						case "f":
							z.IAP.AccFlags = se.Value().AsInt64()
						case "sku":
							z.IAP.SKU = se.Value().StringValue()
						}
					}
				}
			default:
			}
		case 10:
			if bytes.Equal(keyBytes, []byte("onboarding")) {
				{
					subBytes, ok := val.DocumentOK()
					if !ok {
						return fmt.Errorf("field is not document")
					}
					subElems, err := bsoncore.Document(subBytes).Elements()
					if err != nil {
						return err
					}
					for _, se := range subElems {
						switch se.Key() {
						case "ns":
							z.Onboarding.NextStep = se.Value().Int32()
						case "dl":
							{
								if se.Value().Type == 0x0A {
									z.Onboarding.DoneList = nil
									break
								}
								arrBytes, ok := se.Value().ArrayOK()
								if !ok {
									return fmt.Errorf("field is not array")
								}
								arrElems, err := bsoncore.Document(arrBytes).Elements()
								if err != nil {
									return err
								}
								z.Onboarding.DoneList = make([]int32, 0, len(arrElems))
								for _, ae := range arrElems {
									z.Onboarding.DoneList = append(z.Onboarding.DoneList, ae.Value().Int32())
								}
							}
						}
					}
				}
			}
		default:
			// unknown key length — skip
		}
	}
	return nil
}

func (z *IntWidths) MarshalBSON() ([]byte, error) {
	idx, dst := bsoncore.AppendDocumentStart(nil)
	dst = bsoncore.AppendInt32Element(dst, "i8", int32(z.I8))
	dst = bsoncore.AppendInt32Element(dst, "i16", int32(z.I16))
	dst = bsoncore.AppendInt32Element(dst, "i32", z.I32)
	dst = bsoncore.AppendInt64Element(dst, "i64", z.I64)
	dst = bsoncore.AppendInt32Element(dst, "ui8", int32(z.UI8))
	dst = bsoncore.AppendInt32Element(dst, "ui16", int32(z.UI16))
	dst = bsoncore.AppendInt64Element(dst, "ui32", int64(z.UI32))
	if z.UI64 > 9223372036854775807 {
		return nil, fmt.Errorf("字段 %s 超出 int64 范围", "ui64")
	}
	dst = bsoncore.AppendInt64Element(dst, "ui64", int64(z.UI64))
	dst = bsoncore.AppendInt32Element(dst, "int", int32(z.Int))
	if uint64(z.Uint) > 9223372036854775807 {
		return nil, fmt.Errorf("字段 %s 超出 int64 范围", "uint")
	}
	dst = bsoncore.AppendInt64Element(dst, "uint", int64(z.Uint))
	dst, _ = bsoncore.AppendDocumentEnd(dst, idx)
	return dst, nil
}

func (z *IntWidths) UnmarshalBSON(b []byte) error {
	_, data, ok := bsoncore.ReadLength(b)
	if !ok {
		return fmt.Errorf("invalid BSON document")
	}
	for len(data) > 0 && data[0] != 0 {
		elem, rem, ok := bsoncore.ReadElement(data)
		if !ok {
			return fmt.Errorf("invalid BSON element")
		}
		data = rem

		raw := []byte(elem)
		val := elem.Value()

		// Find key length
		keyLen := 0
		for raw[1+keyLen] != 0 {
			keyLen++
		}
		keyBytes := raw[1 : 1+keyLen]

		switch keyLen {
		case 2:
			switch uint64(keyBytes[0])<<0 | uint64(keyBytes[1])<<8 {
			case uint64('i')<<0 | uint64('8')<<8:
				z.I8 = int8(val.AsInt64())
			default:
			}
		case 3:
			switch uint64(keyBytes[0])<<0 | uint64(keyBytes[1])<<8 | uint64(keyBytes[2])<<16 {
			case uint64('i')<<0 | uint64('1')<<8 | uint64('6')<<16:
				z.I16 = int16(val.AsInt64())
			case uint64('i')<<0 | uint64('3')<<8 | uint64('2')<<16:
				z.I32 = val.Int32()
			case uint64('i')<<0 | uint64('6')<<8 | uint64('4')<<16:
				z.I64 = val.AsInt64()
			case uint64('u')<<0 | uint64('i')<<8 | uint64('8')<<16:
				z.UI8 = byte(val.AsInt64())
			case uint64('i')<<0 | uint64('n')<<8 | uint64('t')<<16:
				z.Int = int(val.AsInt64())
			default:
			}
		case 4:
			switch uint64(keyBytes[0])<<0 | uint64(keyBytes[1])<<8 | uint64(keyBytes[2])<<16 | uint64(keyBytes[3])<<24 {
			case uint64('u')<<0 | uint64('i')<<8 | uint64('1')<<16 | uint64('6')<<24:
				z.UI16 = uint16(val.AsInt64())
			case uint64('u')<<0 | uint64('i')<<8 | uint64('3')<<16 | uint64('2')<<24:
				z.UI32 = uint32(val.AsInt64())
			case uint64('u')<<0 | uint64('i')<<8 | uint64('6')<<16 | uint64('4')<<24:
				z.UI64 = uint64(val.AsInt64())
			case uint64('u')<<0 | uint64('i')<<8 | uint64('n')<<16 | uint64('t')<<24:
				z.Uint = uint(val.AsInt64())
			default:
			}
		default:
			// unknown key length — skip
		}
	}
	return nil
}

func (z *ZeroValues) MarshalBSON() ([]byte, error) {
	idx, dst := bsoncore.AppendDocumentStart(nil)
	dst = bsoncore.AppendStringElement(dst, "str", z.Str)
	dst = bsoncore.AppendBooleanElement(dst, "bool", z.Bool)
	dst = bsoncore.AppendInt32Element(dst, "i32", z.I32)
	dst = bsoncore.AppendDoubleElement(dst, "f64", z.F64)
	if z.Bytes == nil {
		dst = bsoncore.AppendNullElement(dst, "bytes")
	} else {
		dst = bsoncore.AppendBinaryElement(dst, "bytes", 0, z.Bytes)
	}
	if z.Slice == nil {
		dst = bsoncore.AppendNullElement(dst, "slice")
	} else {
		aIdx, aDst := bsoncore.AppendArrayStart(nil)
		for i, v := range z.Slice {
			key := strconv.Itoa(i)
			aDst = bsoncore.AppendStringElement(aDst, key, v)
		}
		aDst, _ = bsoncore.AppendArrayEnd(aDst, aIdx)
		dst = bsoncore.AppendArrayElement(dst, "slice", aDst)
	}
	if z.Map == nil {
		dst = bsoncore.AppendNullElement(dst, "map")
	} else {
		mIdx, mDst := bsoncore.AppendDocumentStart(nil)
		for k, v := range z.Map {
			mDst = bsoncore.AppendInt32Element(mDst, k, int32(v))
		}
		mDst, _ = bsoncore.AppendDocumentEnd(mDst, mIdx)
		dst = bsoncore.AppendDocumentElement(dst, "map", mDst)
	}
	if z.Ptr != nil {
		dst = bsoncore.AppendStringElement(dst, "ptr", *z.Ptr)
	} else {
		dst = bsoncore.AppendNullElement(dst, "ptr")
	}
	dst = bsoncore.AppendDateTimeElement(dst, "time", z.Time.UnixMilli())
	if len(z.OptStr) > 0 {
		dst = bsoncore.AppendStringElement(dst, "opt_str", z.OptStr)
	}
	if z.OptI32 != 0 {
		dst = bsoncore.AppendInt32Element(dst, "opt_i32", z.OptI32)
	}
	if z.OptBool {
		dst = bsoncore.AppendBooleanElement(dst, "opt_bool", z.OptBool)
	}
	if z.OptPtr != nil {
		dst = bsoncore.AppendStringElement(dst, "opt_ptr", *z.OptPtr)
	}
	dst, _ = bsoncore.AppendDocumentEnd(dst, idx)
	return dst, nil
}

func (z *ZeroValues) UnmarshalBSON(b []byte) error {
	_, data, ok := bsoncore.ReadLength(b)
	if !ok {
		return fmt.Errorf("invalid BSON document")
	}
	for len(data) > 0 && data[0] != 0 {
		elem, rem, ok := bsoncore.ReadElement(data)
		if !ok {
			return fmt.Errorf("invalid BSON element")
		}
		data = rem

		raw := []byte(elem)
		val := elem.Value()

		// Find key length
		keyLen := 0
		for raw[1+keyLen] != 0 {
			keyLen++
		}
		keyBytes := raw[1 : 1+keyLen]

		switch keyLen {
		case 3:
			switch uint64(keyBytes[0])<<0 | uint64(keyBytes[1])<<8 | uint64(keyBytes[2])<<16 {
			case uint64('s')<<0 | uint64('t')<<8 | uint64('r')<<16:
				z.Str = val.StringValue()
			case uint64('i')<<0 | uint64('3')<<8 | uint64('2')<<16:
				z.I32 = val.Int32()
			case uint64('f')<<0 | uint64('6')<<8 | uint64('4')<<16:
				z.F64 = val.Double()
			case uint64('m')<<0 | uint64('a')<<8 | uint64('p')<<16:
				{
					if val.Type == 0x0A {
						z.Map = nil
						break
					}
					mapBytes, ok := val.DocumentOK()
					if !ok {
						return fmt.Errorf("字段 %s 不是文档类型", "map")
					}
					mapElems, err := bsoncore.Document(mapBytes).Elements()
					if err != nil {
						return err
					}
					z.Map = make(map[string]int, len(mapElems))
					for _, me := range mapElems {
						z.Map[me.Key()] = int(me.Value().AsInt64())
					}
				}
			case uint64('p')<<0 | uint64('t')<<8 | uint64('r')<<16:
				{
					if val.Type == 0x0A {
						z.Ptr = nil
						break
					}
					tmp := val.StringValue()
					z.Ptr = &tmp
				}
			default:
			}
		case 4:
			switch uint64(keyBytes[0])<<0 | uint64(keyBytes[1])<<8 | uint64(keyBytes[2])<<16 | uint64(keyBytes[3])<<24 {
			case uint64('b')<<0 | uint64('o')<<8 | uint64('o')<<16 | uint64('l')<<24:
				z.Bool = val.Boolean()
			case uint64('t')<<0 | uint64('i')<<8 | uint64('m')<<16 | uint64('e')<<24:
				z.Time = primitive.DateTime(val.DateTime()).Time()
			default:
			}
		case 5:
			switch uint64(keyBytes[0])<<0 | uint64(keyBytes[1])<<8 | uint64(keyBytes[2])<<16 | uint64(keyBytes[3])<<24 | uint64(keyBytes[4])<<32 {
			case uint64('b')<<0 | uint64('y')<<8 | uint64('t')<<16 | uint64('e')<<24 | uint64('s')<<32:
				if val.Type == 0x0A {
					z.Bytes = nil
				} else {
					_, z.Bytes, _ = val.BinaryOK()
				}
			case uint64('s')<<0 | uint64('l')<<8 | uint64('i')<<16 | uint64('c')<<24 | uint64('e')<<32:
				{
					if val.Type == 0x0A {
						z.Slice = nil
						break
					}
					arrBytes, ok := val.ArrayOK()
					if !ok {
						return fmt.Errorf("字段 %s 不是数组类型", "slice")
					}
					arrElems, err := bsoncore.Document(arrBytes).Elements()
					if err != nil {
						return err
					}
					z.Slice = make([]string, 0, len(arrElems))
					for _, ae := range arrElems {
						z.Slice = append(z.Slice, ae.Value().StringValue())
					}
				}
			default:
			}
		case 7:
			switch uint64(keyBytes[0])<<0 | uint64(keyBytes[1])<<8 | uint64(keyBytes[2])<<16 | uint64(keyBytes[3])<<24 | uint64(keyBytes[4])<<32 | uint64(keyBytes[5])<<40 | uint64(keyBytes[6])<<48 {
			case uint64('o')<<0 | uint64('p')<<8 | uint64('t')<<16 | uint64('_')<<24 | uint64('s')<<32 | uint64('t')<<40 | uint64('r')<<48:
				z.OptStr = val.StringValue()
			case uint64('o')<<0 | uint64('p')<<8 | uint64('t')<<16 | uint64('_')<<24 | uint64('i')<<32 | uint64('3')<<40 | uint64('2')<<48:
				z.OptI32 = val.Int32()
			case uint64('o')<<0 | uint64('p')<<8 | uint64('t')<<16 | uint64('_')<<24 | uint64('p')<<32 | uint64('t')<<40 | uint64('r')<<48:
				{
					if val.Type == 0x0A {
						z.OptPtr = nil
						break
					}
					tmp := val.StringValue()
					z.OptPtr = &tmp
				}
			default:
			}
		case 8:
			switch uint64(keyBytes[0])<<0 | uint64(keyBytes[1])<<8 | uint64(keyBytes[2])<<16 | uint64(keyBytes[3])<<24 | uint64(keyBytes[4])<<32 | uint64(keyBytes[5])<<40 | uint64(keyBytes[6])<<48 | uint64(keyBytes[7])<<56 {
			case uint64('o')<<0 | uint64('p')<<8 | uint64('t')<<16 | uint64('_')<<24 | uint64('b')<<32 | uint64('o')<<40 | uint64('o')<<48 | uint64('l')<<56:
				z.OptBool = val.Boolean()
			default:
			}
		default:
			// unknown key length — skip
		}
	}
	return nil
}

func (z *BattleStats) MarshalBSON() ([]byte, error) {
	idx, dst := bsoncore.AppendDocumentStart(nil)
	dst = bsoncore.AppendInt32Element(dst, "wins", z.Wins)
	dst = bsoncore.AppendInt32Element(dst, "losses", z.Losses)
	dst = bsoncore.AppendInt32Element(dst, "rating", z.Rating)
	dst, _ = bsoncore.AppendDocumentEnd(dst, idx)
	return dst, nil
}

func (z *BattleStats) UnmarshalBSON(b []byte) error {
	_, data, ok := bsoncore.ReadLength(b)
	if !ok {
		return fmt.Errorf("invalid BSON document")
	}
	for len(data) > 0 && data[0] != 0 {
		elem, rem, ok := bsoncore.ReadElement(data)
		if !ok {
			return fmt.Errorf("invalid BSON element")
		}
		data = rem

		raw := []byte(elem)
		val := elem.Value()

		// Find key length
		keyLen := 0
		for raw[1+keyLen] != 0 {
			keyLen++
		}
		keyBytes := raw[1 : 1+keyLen]

		switch keyLen {
		case 4:
			switch uint64(keyBytes[0])<<0 | uint64(keyBytes[1])<<8 | uint64(keyBytes[2])<<16 | uint64(keyBytes[3])<<24 {
			case uint64('w')<<0 | uint64('i')<<8 | uint64('n')<<16 | uint64('s')<<24:
				z.Wins = val.Int32()
			default:
			}
		case 6:
			switch uint64(keyBytes[0])<<0 | uint64(keyBytes[1])<<8 | uint64(keyBytes[2])<<16 | uint64(keyBytes[3])<<24 | uint64(keyBytes[4])<<32 | uint64(keyBytes[5])<<40 {
			case uint64('l')<<0 | uint64('o')<<8 | uint64('s')<<16 | uint64('s')<<24 | uint64('e')<<32 | uint64('s')<<40:
				z.Losses = val.Int32()
			case uint64('r')<<0 | uint64('a')<<8 | uint64('t')<<16 | uint64('i')<<24 | uint64('n')<<32 | uint64('g')<<40:
				z.Rating = val.Int32()
			default:
			}
		default:
			// unknown key length — skip
		}
	}
	return nil
}

func (z *Bag) MarshalBSON() ([]byte, error) {
	idx, dst := bsoncore.AppendDocumentStart(nil)
	dst = bsoncore.AppendInt64Element(dst, "gold", z.Gold)
	if z.Items == nil {
		dst = bsoncore.AppendNullElement(dst, "items")
	} else {
		aIdx, aDst := bsoncore.AppendArrayStart(nil)
		for i, v := range z.Items {
			key := strconv.Itoa(i)
			aDst = bsoncore.AppendInt32Element(aDst, key, v)
		}
		aDst, _ = bsoncore.AppendArrayEnd(aDst, aIdx)
		dst = bsoncore.AppendArrayElement(dst, "items", aDst)
	}
	dst, _ = bsoncore.AppendDocumentEnd(dst, idx)
	return dst, nil
}

func (z *Bag) UnmarshalBSON(b []byte) error {
	_, data, ok := bsoncore.ReadLength(b)
	if !ok {
		return fmt.Errorf("invalid BSON document")
	}
	for len(data) > 0 && data[0] != 0 {
		elem, rem, ok := bsoncore.ReadElement(data)
		if !ok {
			return fmt.Errorf("invalid BSON element")
		}
		data = rem

		raw := []byte(elem)
		val := elem.Value()

		// Find key length
		keyLen := 0
		for raw[1+keyLen] != 0 {
			keyLen++
		}
		keyBytes := raw[1 : 1+keyLen]

		switch keyLen {
		case 4:
			switch uint64(keyBytes[0])<<0 | uint64(keyBytes[1])<<8 | uint64(keyBytes[2])<<16 | uint64(keyBytes[3])<<24 {
			case uint64('g')<<0 | uint64('o')<<8 | uint64('l')<<16 | uint64('d')<<24:
				z.Gold = val.AsInt64()
			default:
			}
		case 5:
			switch uint64(keyBytes[0])<<0 | uint64(keyBytes[1])<<8 | uint64(keyBytes[2])<<16 | uint64(keyBytes[3])<<24 | uint64(keyBytes[4])<<32 {
			case uint64('i')<<0 | uint64('t')<<8 | uint64('e')<<16 | uint64('m')<<24 | uint64('s')<<32:
				{
					if val.Type == 0x0A {
						z.Items = nil
						break
					}
					arrBytes, ok := val.ArrayOK()
					if !ok {
						return fmt.Errorf("字段 %s 不是数组类型", "items")
					}
					arrElems, err := bsoncore.Document(arrBytes).Elements()
					if err != nil {
						return err
					}
					z.Items = make([]int32, 0, len(arrElems))
					for _, ae := range arrElems {
						z.Items = append(z.Items, ae.Value().Int32())
					}
				}
			default:
			}
		default:
			// unknown key length — skip
		}
	}
	return nil
}

func (z *Player) MarshalBSON() ([]byte, error) {
	idx, dst := bsoncore.AppendDocumentStart(nil)
	dst = bsoncore.AppendInt64Element(dst, "_id", z.ID)
	dst = bsoncore.AppendInt64Element(dst, "account_id", z.AccountID)
	dst = bsoncore.AppendStringElement(dst, "name", z.Name)
	dst = bsoncore.AppendInt32Element(dst, "lv", z.Level)
	dst = bsoncore.AppendInt32Element(dst, "exp", z.Exp)
	dst = bsoncore.AppendInt32Element(dst, "head", z.Head)
	dst = bsoncore.AppendInt32Element(dst, "vip", z.VipLevel)
	dst = bsoncore.AppendInt32Element(dst, "tag", z.Tag)
	dst = bsoncore.AppendInt32Element(dst, "rate", int32(z.Rate))
	dst = bsoncore.AppendBooleanElement(dst, "load", z.Load)
	dst = bsoncore.AppendBooleanElement(dst, "renamed", z.HasRenamed)
	if z.OfflineFight != nil {
		{
			aj, ajDst := bsoncore.AppendDocumentStart(nil)
			ajDst = bsoncore.AppendInt32Element(ajDst, "id", z.OfflineFight.ID)
			ajDst = bsoncore.AppendStringElement(ajDst, "name", z.OfflineFight.Name)
			ajDst = bsoncore.AppendInt32Element(ajDst, "hp", z.OfflineFight.HP)
			ajDst = bsoncore.AppendInt32Element(ajDst, "mp", z.OfflineFight.MP)
			ajDst, _ = bsoncore.AppendDocumentEnd(ajDst, aj)
			dst = bsoncore.AppendDocumentElement(dst, "offline_fight", ajDst)
		}
	}
	if len(z.Heros) > 0 {
		aIdx, aDst := bsoncore.AppendArrayStart(nil)
		for i, v := range z.Heros {
			key := strconv.Itoa(i)
			if v != nil {
				{
					subIdx, subDst := bsoncore.AppendDocumentStart(nil)
					subDst = bsoncore.AppendInt32Element(subDst, "id", (*v).ID)
					subDst = bsoncore.AppendStringElement(subDst, "name", (*v).Name)
					subDst = bsoncore.AppendInt32Element(subDst, "hp", (*v).HP)
					subDst = bsoncore.AppendInt32Element(subDst, "mp", (*v).MP)
					subDst, _ = bsoncore.AppendDocumentEnd(subDst, subIdx)
					aDst = bsoncore.AppendDocumentElement(aDst, key, subDst)
				}
			} else {
				aDst = bsoncore.AppendNullElement(aDst, key)
			}
		}
		aDst, _ = bsoncore.AppendArrayEnd(aDst, aIdx)
		dst = bsoncore.AppendArrayElement(dst, "heros", aDst)
	}
	{
		subBytes, err := z.Bag.MarshalBSON()
		if err != nil {
			return nil, err
		}
		dst = bsoncore.AppendDocumentElement(dst, "bag", subBytes)
	}
	if len(z.SalePackages) > 0 {
		aIdx, aDst := bsoncore.AppendArrayStart(nil)
		for i, v := range z.SalePackages {
			key := strconv.Itoa(i)
			if v != nil {
				{
					subBytes, err := bson.Marshal((*v))
					if err != nil {
						return nil, err
					}
					aDst = bsoncore.AppendDocumentElement(aDst, key, subBytes)
				}
			} else {
				aDst = bsoncore.AppendNullElement(aDst, key)
			}
		}
		aDst, _ = bsoncore.AppendArrayEnd(aDst, aIdx)
		dst = bsoncore.AppendArrayElement(dst, "sale_pkgs", aDst)
	}
	if len(z.ClientFilter) > 0 {
		aIdx, aDst := bsoncore.AppendArrayStart(nil)
		for i, v := range z.ClientFilter {
			key := strconv.Itoa(i)
			{
				innerIdx, innerDst := bsoncore.AppendArrayStart(nil)
				for i, v := range v {
					k := strconv.Itoa(i)
					innerDst = bsoncore.AppendInt32Element(innerDst, k, v)
				}
				innerDst, _ = bsoncore.AppendArrayEnd(innerDst, innerIdx)
				aDst = bsoncore.AppendArrayElement(aDst, key, innerDst)
			}
		}
		aDst, _ = bsoncore.AppendArrayEnd(aDst, aIdx)
		dst = bsoncore.AppendArrayElement(dst, "cdf", aDst)
	}
	if len(z.PBCounters) > 0 {
		aIdx, aDst := bsoncore.AppendArrayStart(nil)
		for i, v := range z.PBCounters {
			key := strconv.Itoa(i)
			{
				subBytes, err := bson.Marshal(v)
				if err != nil {
					return nil, err
				}
				aDst = bsoncore.AppendDocumentElement(aDst, key, subBytes)
			}
		}
		aDst, _ = bsoncore.AppendArrayEnd(aDst, aIdx)
		dst = bsoncore.AppendArrayElement(dst, "pbcs", aDst)
	}
	if z.BossDropSeqs == nil {
		dst = bsoncore.AppendNullElement(dst, "bds")
	} else {
		aIdx, aDst := bsoncore.AppendArrayStart(nil)
		for i, v := range z.BossDropSeqs {
			key := strconv.Itoa(i)
			{
				subBytes, err := bson.Marshal(v)
				if err != nil {
					return nil, err
				}
				aDst = bsoncore.AppendDocumentElement(aDst, key, subBytes)
			}
		}
		aDst, _ = bsoncore.AppendArrayEnd(aDst, aIdx)
		dst = bsoncore.AppendArrayElement(dst, "bds", aDst)
	}
	if z.Bids == nil {
		dst = bsoncore.AppendNullElement(dst, "bids")
	} else {
		aIdx, aDst := bsoncore.AppendArrayStart(nil)
		for i, v := range z.Bids {
			key := strconv.Itoa(i)
			aDst = bsoncore.AppendStringElement(aDst, key, v)
		}
		aDst, _ = bsoncore.AppendArrayEnd(aDst, aIdx)
		dst = bsoncore.AppendArrayElement(dst, "bids", aDst)
	}
	if len(z.SubChan) > 0 {
		aIdx, aDst := bsoncore.AppendArrayStart(nil)
		for i, v := range z.SubChan {
			key := strconv.Itoa(i)
			aDst = bsoncore.AppendStringElement(aDst, key, v)
		}
		aDst, _ = bsoncore.AppendArrayEnd(aDst, aIdx)
		dst = bsoncore.AppendArrayElement(dst, "sub_chan", aDst)
	}
	if len(z.ActiveContracts) > 0 {
		aIdx, aDst := bsoncore.AppendArrayStart(nil)
		for i, v := range z.ActiveContracts {
			key := strconv.Itoa(i)
			aDst = bsoncore.AppendInt32Element(aDst, key, v)
		}
		aDst, _ = bsoncore.AppendArrayEnd(aDst, aIdx)
		dst = bsoncore.AppendArrayElement(dst, "contracts", aDst)
	}
	dst = bsoncore.AppendInt32Element(dst, "nid", int32(z.AutoIncrementID))
	{
		subBytes, err := z.Statue.MarshalBSON()
		if err != nil {
			return nil, err
		}
		dst = bsoncore.AppendDocumentElement(dst, "statues", subBytes)
	}
	dst, _ = bsoncore.AppendDocumentEnd(dst, idx)
	return dst, nil
}

func (z *Player) UnmarshalBSON(b []byte) error {
	_, data, ok := bsoncore.ReadLength(b)
	if !ok {
		return fmt.Errorf("invalid BSON document")
	}
	for len(data) > 0 && data[0] != 0 {
		elem, rem, ok := bsoncore.ReadElement(data)
		if !ok {
			return fmt.Errorf("invalid BSON element")
		}
		data = rem

		raw := []byte(elem)
		val := elem.Value()

		// Find key length
		keyLen := 0
		for raw[1+keyLen] != 0 {
			keyLen++
		}
		keyBytes := raw[1 : 1+keyLen]

		switch keyLen {
		case 2:
			switch uint64(keyBytes[0])<<0 | uint64(keyBytes[1])<<8 {
			case uint64('l')<<0 | uint64('v')<<8:
				z.Level = val.Int32()
			default:
			}
		case 3:
			switch uint64(keyBytes[0])<<0 | uint64(keyBytes[1])<<8 | uint64(keyBytes[2])<<16 {
			case uint64('_')<<0 | uint64('i')<<8 | uint64('d')<<16:
				z.ID = val.AsInt64()
			case uint64('e')<<0 | uint64('x')<<8 | uint64('p')<<16:
				z.Exp = val.Int32()
			case uint64('v')<<0 | uint64('i')<<8 | uint64('p')<<16:
				z.VipLevel = val.Int32()
			case uint64('t')<<0 | uint64('a')<<8 | uint64('g')<<16:
				z.Tag = val.Int32()
			case uint64('b')<<0 | uint64('a')<<8 | uint64('g')<<16:
				{
					subBytes, ok := val.DocumentOK()
					if !ok {
						return fmt.Errorf("字段 %s 不是文档类型", "bag")
					}
					if err := z.Bag.UnmarshalBSON(subBytes); err != nil {
						return err
					}
				}
			case uint64('c')<<0 | uint64('d')<<8 | uint64('f')<<16:
				{
					if val.Type == 0x0A {
						z.ClientFilter = nil
						break
					}
					arrBytes, ok := val.ArrayOK()
					if !ok {
						return fmt.Errorf("字段 %s 不是数组类型", "cdf")
					}
					arrElems, err := bsoncore.Document(arrBytes).Elements()
					if err != nil {
						return err
					}
					z.ClientFilter = make([][]int32, 0, len(arrElems))
					for _, ae := range arrElems {
						{
							subArrBytes11, subArrOK12 := ae.Value().ArrayOK()
							if !subArrOK12 {
								return fmt.Errorf("数组元素不是数组类型")
							}
							subArrElems13, subArrErr14 := bsoncore.Document(subArrBytes11).Elements()
							if subArrErr14 != nil {
								return subArrErr14
							}
							subItem15 := make([]int32, 0, len(subArrElems13))
							for _, sae := range subArrElems13 {
								subItem15 = append(subItem15, sae.Value().Int32())
							}
							z.ClientFilter = append(z.ClientFilter, subItem15)
						}
					}
				}
			case uint64('b')<<0 | uint64('d')<<8 | uint64('s')<<16:
				{
					if val.Type == 0x0A {
						z.BossDropSeqs = nil
						break
					}
					arrBytes, ok := val.ArrayOK()
					if !ok {
						return fmt.Errorf("字段 %s 不是数组类型", "bds")
					}
					arrElems, err := bsoncore.Document(arrBytes).Elements()
					if err != nil {
						return err
					}
					z.BossDropSeqs = make([]map[string]int64, 0, len(arrElems))
					for _, ae := range arrElems {
						{
							subMapBytes16, subMapOK17 := ae.Value().DocumentOK()
							if !subMapOK17 {
								return fmt.Errorf("数组元素不是文档类型")
							}
							subMapElems18, subMapErr19 := bsoncore.Document(subMapBytes16).Elements()
							if subMapErr19 != nil {
								return subMapErr19
							}
							subItem20 := make(map[string]int64, len(subMapElems18))
							for _, sme := range subMapElems18 {
								subItem20[sme.Key()] = sme.Value().AsInt64()
							}
							z.BossDropSeqs = append(z.BossDropSeqs, subItem20)
						}
					}
				}
			case uint64('n')<<0 | uint64('i')<<8 | uint64('d')<<16:
				z.AutoIncrementID = int(val.AsInt64())
			default:
			}
		case 4:
			switch uint64(keyBytes[0])<<0 | uint64(keyBytes[1])<<8 | uint64(keyBytes[2])<<16 | uint64(keyBytes[3])<<24 {
			case uint64('n')<<0 | uint64('a')<<8 | uint64('m')<<16 | uint64('e')<<24:
				z.Name = val.StringValue()
			case uint64('h')<<0 | uint64('e')<<8 | uint64('a')<<16 | uint64('d')<<24:
				z.Head = val.Int32()
			case uint64('r')<<0 | uint64('a')<<8 | uint64('t')<<16 | uint64('e')<<24:
				z.Rate = int8(val.AsInt64())
			case uint64('l')<<0 | uint64('o')<<8 | uint64('a')<<16 | uint64('d')<<24:
				z.Load = val.Boolean()
			case uint64('p')<<0 | uint64('b')<<8 | uint64('c')<<16 | uint64('s')<<24:
				{
					if val.Type == 0x0A {
						z.PBCounters = nil
						break
					}
					arrBytes, ok := val.ArrayOK()
					if !ok {
						return fmt.Errorf("字段 %s 不是数组类型", "pbcs")
					}
					arrElems, err := bsoncore.Document(arrBytes).Elements()
					if err != nil {
						return err
					}
					z.PBCounters = make([]map[string]int64, 0, len(arrElems))
					for _, ae := range arrElems {
						{
							subMapBytes21, subMapOK22 := ae.Value().DocumentOK()
							if !subMapOK22 {
								return fmt.Errorf("数组元素不是文档类型")
							}
							subMapElems23, subMapErr24 := bsoncore.Document(subMapBytes21).Elements()
							if subMapErr24 != nil {
								return subMapErr24
							}
							subItem25 := make(map[string]int64, len(subMapElems23))
							for _, sme := range subMapElems23 {
								subItem25[sme.Key()] = sme.Value().AsInt64()
							}
							z.PBCounters = append(z.PBCounters, subItem25)
						}
					}
				}
			case uint64('b')<<0 | uint64('i')<<8 | uint64('d')<<16 | uint64('s')<<24:
				{
					if val.Type == 0x0A {
						z.Bids = nil
						break
					}
					arrBytes, ok := val.ArrayOK()
					if !ok {
						return fmt.Errorf("字段 %s 不是数组类型", "bids")
					}
					arrElems, err := bsoncore.Document(arrBytes).Elements()
					if err != nil {
						return err
					}
					z.Bids = make([]string, 0, len(arrElems))
					for _, ae := range arrElems {
						z.Bids = append(z.Bids, ae.Value().StringValue())
					}
				}
			default:
			}
		case 5:
			switch uint64(keyBytes[0])<<0 | uint64(keyBytes[1])<<8 | uint64(keyBytes[2])<<16 | uint64(keyBytes[3])<<24 | uint64(keyBytes[4])<<32 {
			case uint64('h')<<0 | uint64('e')<<8 | uint64('r')<<16 | uint64('o')<<24 | uint64('s')<<32:
				{
					if val.Type == 0x0A {
						z.Heros = nil
						break
					}
					arrBytes, ok := val.ArrayOK()
					if !ok {
						return fmt.Errorf("字段 %s 不是数组类型", "heros")
					}
					arrElems, err := bsoncore.Document(arrBytes).Elements()
					if err != nil {
						return err
					}
					z.Heros = make([]*Hero, 0, len(arrElems))
					for _, ae := range arrElems {
						{
							if ae.Value().Type == 0x0A {
								z.Heros = append(z.Heros, nil)
							} else {
								subBytes, ok := ae.Value().DocumentOK()
								if !ok {
									return fmt.Errorf("数组元素不是文档类型")
								}
								subItem := new(Hero)
								subBytes26, subOK27 := bsoncore.Value{Type: 0x03, Data: subBytes}.DocumentOK()
								if !subOK27 {
									return fmt.Errorf("字段 %s 不是文档类型", "数组元素")
								}
								subElems28, subErr29 := bsoncore.Document(subBytes26).Elements()
								if subErr29 != nil {
									return subErr29
								}
								for _, subElem30 := range subElems28 {
									switch subElem30.Key() {
									case "id":
										subItem.ID = subElem30.Value().Int32()
									case "name":
										subItem.Name = subElem30.Value().StringValue()
									case "hp":
										subItem.HP = subElem30.Value().Int32()
									case "mp":
										subItem.MP = subElem30.Value().Int32()
									}
								}
								z.Heros = append(z.Heros, subItem)
							}
						}
					}
				}
			default:
			}
		case 7:
			switch uint64(keyBytes[0])<<0 | uint64(keyBytes[1])<<8 | uint64(keyBytes[2])<<16 | uint64(keyBytes[3])<<24 | uint64(keyBytes[4])<<32 | uint64(keyBytes[5])<<40 | uint64(keyBytes[6])<<48 {
			case uint64('r')<<0 | uint64('e')<<8 | uint64('n')<<16 | uint64('a')<<24 | uint64('m')<<32 | uint64('e')<<40 | uint64('d')<<48:
				z.HasRenamed = val.Boolean()
			case uint64('s')<<0 | uint64('t')<<8 | uint64('a')<<16 | uint64('t')<<24 | uint64('u')<<32 | uint64('e')<<40 | uint64('s')<<48:
				{
					subBytes, ok := val.DocumentOK()
					if !ok {
						return fmt.Errorf("字段 %s 不是文档类型", "statues")
					}
					if err := z.Statue.UnmarshalBSON(subBytes); err != nil {
						return err
					}
				}
			default:
			}
		case 8:
			switch uint64(keyBytes[0])<<0 | uint64(keyBytes[1])<<8 | uint64(keyBytes[2])<<16 | uint64(keyBytes[3])<<24 | uint64(keyBytes[4])<<32 | uint64(keyBytes[5])<<40 | uint64(keyBytes[6])<<48 | uint64(keyBytes[7])<<56 {
			case uint64('s')<<0 | uint64('u')<<8 | uint64('b')<<16 | uint64('_')<<24 | uint64('c')<<32 | uint64('h')<<40 | uint64('a')<<48 | uint64('n')<<56:
				{
					if val.Type == 0x0A {
						z.SubChan = nil
						break
					}
					arrBytes, ok := val.ArrayOK()
					if !ok {
						return fmt.Errorf("字段 %s 不是数组类型", "sub_chan")
					}
					arrElems, err := bsoncore.Document(arrBytes).Elements()
					if err != nil {
						return err
					}
					z.SubChan = make([]string, 0, len(arrElems))
					for _, ae := range arrElems {
						z.SubChan = append(z.SubChan, ae.Value().StringValue())
					}
				}
			default:
			}
		case 9:
			if bytes.Equal(keyBytes, []byte("sale_pkgs")) {
				{
					if val.Type == 0x0A {
						z.SalePackages = nil
						break
					}
					arrBytes, ok := val.ArrayOK()
					if !ok {
						return fmt.Errorf("字段 %s 不是数组类型", "sale_pkgs")
					}
					arrElems, err := bsoncore.Document(arrBytes).Elements()
					if err != nil {
						return err
					}
					z.SalePackages = make([]*struct {
						ID   int32  `bson:"id"`
						Name string `bson:"name"`
					}, 0, len(arrElems))
					for _, ae := range arrElems {
						{
							subBytes, ok := ae.Value().DocumentOK()
							if !ok {
								return fmt.Errorf("数组元素不是文档类型")
							}
							var subItem *struct {
								ID   int32  `bson:"id"`
								Name string `bson:"name"`
							}
							if err := bson.Unmarshal(subBytes, &subItem); err != nil {
								return err
							}
							z.SalePackages = append(z.SalePackages, subItem)
						}
					}
				}
			} else if bytes.Equal(keyBytes, []byte("contracts")) {
				{
					if val.Type == 0x0A {
						z.ActiveContracts = nil
						break
					}
					arrBytes, ok := val.ArrayOK()
					if !ok {
						return fmt.Errorf("字段 %s 不是数组类型", "contracts")
					}
					arrElems, err := bsoncore.Document(arrBytes).Elements()
					if err != nil {
						return err
					}
					z.ActiveContracts = make([]int32, 0, len(arrElems))
					for _, ae := range arrElems {
						z.ActiveContracts = append(z.ActiveContracts, ae.Value().Int32())
					}
				}
			}
		case 10:
			if bytes.Equal(keyBytes, []byte("account_id")) {
				z.AccountID = val.AsInt64()
			}
		case 13:
			if bytes.Equal(keyBytes, []byte("offline_fight")) {
				{
					if val.Type == 0x0A {
						z.OfflineFight = nil
						break
					}
					val, ok := val.DocumentOK()
					if ok {
						z.OfflineFight = new(Hero)
						subBytes31, subOK32 := bsoncore.Value{Type: 0x03, Data: val}.DocumentOK()
						if !subOK32 {
							return fmt.Errorf("字段 %s 不是文档类型", "offline_fight")
						}
						subElems33, subErr34 := bsoncore.Document(subBytes31).Elements()
						if subErr34 != nil {
							return subErr34
						}
						for _, subElem35 := range subElems33 {
							switch subElem35.Key() {
							case "id":
								z.OfflineFight.ID = subElem35.Value().Int32()
							case "name":
								z.OfflineFight.Name = subElem35.Value().StringValue()
							case "hp":
								z.OfflineFight.HP = subElem35.Value().Int32()
							case "mp":
								z.OfflineFight.MP = subElem35.Value().Int32()
							}
						}
					} else {
						z.OfflineFight = nil
					}
				}
			}
		default:
			// unknown key length — skip
		}
	}
	return nil
}

func (z *StatueInfo) MarshalBSON() ([]byte, error) {
	idx, dst := bsoncore.AppendDocumentStart(nil)
	dst = bsoncore.AppendInt32Element(dst, "c", z.Count)
	dst = bsoncore.AppendBooleanElement(dst, "active", z.Active)
	dst, _ = bsoncore.AppendDocumentEnd(dst, idx)
	return dst, nil
}

func (z *StatueInfo) UnmarshalBSON(b []byte) error {
	_, data, ok := bsoncore.ReadLength(b)
	if !ok {
		return fmt.Errorf("invalid BSON document")
	}
	for len(data) > 0 && data[0] != 0 {
		elem, rem, ok := bsoncore.ReadElement(data)
		if !ok {
			return fmt.Errorf("invalid BSON element")
		}
		data = rem

		raw := []byte(elem)
		val := elem.Value()

		// Find key length
		keyLen := 0
		for raw[1+keyLen] != 0 {
			keyLen++
		}
		keyBytes := raw[1 : 1+keyLen]

		switch keyLen {
		case 1:
			switch uint64(keyBytes[0]) << 0 {
			case uint64('c') << 0:
				z.Count = val.Int32()
			default:
			}
		case 6:
			switch uint64(keyBytes[0])<<0 | uint64(keyBytes[1])<<8 | uint64(keyBytes[2])<<16 | uint64(keyBytes[3])<<24 | uint64(keyBytes[4])<<32 | uint64(keyBytes[5])<<40 {
			case uint64('a')<<0 | uint64('c')<<8 | uint64('t')<<16 | uint64('i')<<24 | uint64('v')<<32 | uint64('e')<<40:
				z.Active = val.Boolean()
			default:
			}
		default:
			// unknown key length — skip
		}
	}
	return nil
}

func (z *WideStruct) MarshalBSON() ([]byte, error) {
	idx, dst := bsoncore.AppendDocumentStart(nil)
	dst = bsoncore.AppendInt32Element(dst, "a", z.A)
	dst = bsoncore.AppendInt32Element(dst, "b", z.B)
	dst = bsoncore.AppendInt32Element(dst, "c", z.C)
	dst = bsoncore.AppendInt32Element(dst, "d", z.D)
	dst = bsoncore.AppendInt32Element(dst, "e", z.E)
	dst = bsoncore.AppendInt32Element(dst, "f", z.F)
	dst = bsoncore.AppendInt32Element(dst, "g", z.G)
	dst = bsoncore.AppendInt32Element(dst, "h", z.H)
	dst = bsoncore.AppendInt32Element(dst, "i", z.I)
	dst = bsoncore.AppendInt32Element(dst, "j", z.J)
	dst = bsoncore.AppendInt32Element(dst, "k", z.K)
	dst = bsoncore.AppendInt32Element(dst, "l", z.L)
	dst = bsoncore.AppendInt32Element(dst, "m", z.M)
	dst = bsoncore.AppendInt32Element(dst, "n", z.N)
	dst = bsoncore.AppendInt32Element(dst, "o", z.O)
	dst = bsoncore.AppendInt32Element(dst, "p", z.P)
	dst = bsoncore.AppendInt32Element(dst, "q", z.Q)
	dst = bsoncore.AppendInt32Element(dst, "r", z.R)
	dst = bsoncore.AppendInt32Element(dst, "s", z.S)
	dst = bsoncore.AppendInt32Element(dst, "t", z.T)
	dst = bsoncore.AppendInt32Element(dst, "u", z.U)
	dst = bsoncore.AppendInt32Element(dst, "v", z.V)
	dst = bsoncore.AppendInt32Element(dst, "w", z.W)
	dst = bsoncore.AppendInt32Element(dst, "x", z.X)
	dst = bsoncore.AppendInt32Element(dst, "y", z.Y)
	dst = bsoncore.AppendInt32Element(dst, "z", z.Z)
	dst, _ = bsoncore.AppendDocumentEnd(dst, idx)
	return dst, nil
}

func (z *WideStruct) UnmarshalBSON(b []byte) error {
	_, data, ok := bsoncore.ReadLength(b)
	if !ok {
		return fmt.Errorf("invalid BSON document")
	}
	for len(data) > 0 && data[0] != 0 {
		elem, rem, ok := bsoncore.ReadElement(data)
		if !ok {
			return fmt.Errorf("invalid BSON element")
		}
		data = rem

		raw := []byte(elem)
		val := elem.Value()

		// Find key length
		keyLen := 0
		for raw[1+keyLen] != 0 {
			keyLen++
		}
		keyBytes := raw[1 : 1+keyLen]

		switch keyLen {
		case 1:
			switch uint64(keyBytes[0]) << 0 {
			case uint64('a') << 0:
				z.A = val.Int32()
			case uint64('b') << 0:
				z.B = val.Int32()
			case uint64('c') << 0:
				z.C = val.Int32()
			case uint64('d') << 0:
				z.D = val.Int32()
			case uint64('e') << 0:
				z.E = val.Int32()
			case uint64('f') << 0:
				z.F = val.Int32()
			case uint64('g') << 0:
				z.G = val.Int32()
			case uint64('h') << 0:
				z.H = val.Int32()
			case uint64('i') << 0:
				z.I = val.Int32()
			case uint64('j') << 0:
				z.J = val.Int32()
			case uint64('k') << 0:
				z.K = val.Int32()
			case uint64('l') << 0:
				z.L = val.Int32()
			case uint64('m') << 0:
				z.M = val.Int32()
			case uint64('n') << 0:
				z.N = val.Int32()
			case uint64('o') << 0:
				z.O = val.Int32()
			case uint64('p') << 0:
				z.P = val.Int32()
			case uint64('q') << 0:
				z.Q = val.Int32()
			case uint64('r') << 0:
				z.R = val.Int32()
			case uint64('s') << 0:
				z.S = val.Int32()
			case uint64('t') << 0:
				z.T = val.Int32()
			case uint64('u') << 0:
				z.U = val.Int32()
			case uint64('v') << 0:
				z.V = val.Int32()
			case uint64('w') << 0:
				z.W = val.Int32()
			case uint64('x') << 0:
				z.X = val.Int32()
			case uint64('y') << 0:
				z.Y = val.Int32()
			case uint64('z') << 0:
				z.Z = val.Int32()
			default:
			}
		default:
			// unknown key length — skip
		}
	}
	return nil
}
